import { initializeApp, cert } from "firebase-admin/app";
import { getFirestore, FieldValue } from "firebase-admin/firestore";
import fs from "fs";

// Load Firebase config
const serviceAccount = JSON.parse(fs.readFileSync('./serviceAccountKey.json', 'utf8'));
const app = initializeApp({
  credential: cert(serviceAccount)
});
const db = getFirestore(app);

async function runTest() {
  console.log("=== VERIFYING E2E PRO-PANEL STREAM FLOW ===\n");

  const bookingId = "TEST_BOOKING_" + Date.now();
  const streamId = "stream_" + Date.now();
  const templeId = "TEST_TEMPLE";

  // 1. Create a Confirmed Booking
  console.log(`[1] Creating Booking ${bookingId} with bookingStatus = "Confirmed"...`);
  await db.collection("bookings").doc(bookingId).set({
    templeId,
    poojaId: "TEST_POOJA",
    userId: "TEST_USER",
    bookingStatus: "Confirmed",
    isDeleted: false,
    createdAt: FieldValue.serverTimestamp()
  });

  // 2. Start Stream (Pro Panel Logic from LiveStream.tsx)
  console.log(`[2] Starting stream via pro-panel logic (LiveStream.tsx:80)...`);
  await db.collection('bookings').doc(bookingId).update({
    status: 'IN_PROGRESS',
    streamId: streamId,
    streamStatus: 'LIVE'
  });

  await db.collection('liveStreams').doc(streamId).set({
    streamId,
    bookingId: bookingId,
    templeId: templeId,
    poojaId: "TEST_POOJA",
    streamUrl: `rtmp://live.doshanivarana.com/app/${streamId}`,
    status: 'LIVE',
    createdAt: FieldValue.serverTimestamp()
  });

  // 3. End Stream (Pro Panel Logic from LiveStream.tsx)
  console.log(`[3] Ending stream via pro-panel logic (LiveStream.tsx:173)...`);
  await db.collection('liveStreams').doc(streamId).update({
    status: 'ENDED',
    endedAt: FieldValue.serverTimestamp()
  });

  await db.collection('bookings').doc(bookingId).update({
    status: 'COMPLETED',
    streamStatus: 'ENDED',
    recordingStatus: 'Available'
  });

  // 4. Verification Check
  console.log(`\n[4] VERIFICATION CHECK:`);
  
  // Pro Panel writes to 'liveStreams'
  const liveStreamsDoc = await db.collection("liveStreams").doc(streamId).get();
  console.log(`Document in 'liveStreams' (Pro Panel target) exists: ${liveStreamsDoc.exists}`);
  if (liveStreamsDoc.exists) {
    console.log("Payload:", JSON.stringify(liveStreamsDoc.data(), null, 2));
  }

  // Admin Panel reads from 'live_streams'
  const live_streamsDoc = await db.collection("live_streams").doc(streamId).get();
  console.log(`\nDocument in 'live_streams' (Admin Panel target) exists: ${live_streamsDoc.exists}`);
  if (live_streamsDoc.exists) {
    console.log("Payload:", JSON.stringify(live_streamsDoc.data(), null, 2));
  }

  // Admin Panel expected Recording Logic
  console.log(`\n[5] Can Recording be generated by Admin Panel?`);
  console.log("Admin panel looks for stream status == 'Ended' inside 'live_streams' collection.");
  
  if (live_streamsDoc.exists) {
    const data = live_streamsDoc.data();
    if (data.streamStatus === 'Ended' || data.streamStatus === 'Archived') {
       console.log("SUCCESS: Admin Panel will allow recording generation.");
    } else {
       console.log(`FAILURE: Admin Panel expects streamStatus == 'Ended' or 'Archived', but found: ${data.streamStatus}`);
    }
  } else {
    console.log("FAILURE: Admin Panel cannot see this stream at all because it's in the wrong collection!");
  }

  // Clean up
  console.log("\nCleaning up test documents...");
  await db.collection("bookings").doc(bookingId).update({ isDeleted: true });
  await db.collection("liveStreams").doc(streamId).delete();
  console.log("Done.");
  process.exit(0);
}

runTest().catch(console.error);
