import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'te' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const toggleLanguage = () => {
    const languages: Language[] = ['en', 'te', 'hi', 'gu'];
    const currentIndex = languages.indexOf(language);
    const nextIndex = (currentIndex + 1) % languages.length;
    setLanguage(languages[nextIndex]);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  useEffect(() => {
    // In React Native, handle RTL or other locale-specific behavior if needed
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Comprehensive Translations
const translations: Record<Language, any> = {
  en: {
    common: {
      search: 'Search poojas...',
      viewAll: 'View All',
      upcoming: 'Upcoming',
      active: 'Active',
      completed: 'Completed',
      cancel: 'Cancel',
      save: 'Save',
      continue: 'Continue',
      back: 'Back',
      edit: 'Edit',
      signOut: 'Sign Out',
      close: 'Close',
      viewDetails: 'View Details',
      bookNow: 'Book Now',
      free: 'Free',
      included: 'Included',
      clearAll: 'Clear All',
      signIn: 'Sign In',
      offerSeva: 'Offer Seva',
      tomorrow: 'Tomorrow',
      optional: 'Optional',
    },
    nav: {
      home: 'Home',
      poojas: 'Poojas',
      bookings: 'Bookings',
      temples: 'Temples',
      profile: 'Profile',
    },
    home: {
      greeting: 'Namaste',
      subtitle: 'Today is Ekadashi — an auspicious day for Vishnu poojas.',
      featuredTemples: 'Featured Temples',
      categories: 'Pooja Categories',
      upcomingPoojas: 'Upcoming Poojas',
      notifications: 'Notifications',
      noNotifications: 'No new notifications',
      viewNotification: 'View',
      recommendedForYou: 'Recommended for You',
      basedOnNakshatra: 'Based on your Nakshatra',
      nextLivePooja: 'Next Live Pooja',
      nextLivePoojaName: 'Rudrabhishek at Sri Kalahasti',
      offerSevaAmount: 'Offer Seva — ₹1,100',
      upcoming: 'UPCOMING',
      temples: 'Temples',
      forYou: 'For You',
      live: 'Live',
      poojasCount: '{count} Poojas',
      today: 'Today',
      ekadashi: 'Ekadashi',
      purnima: 'Purnima',
      wed: 'Wed',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
      sun: 'Sun',
      mon: 'Mon',
      tue: 'Tue',
      lakshmiPooja: 'Lakshmi Pooja',
      maduraiTemple: 'Madurai Temple',
      rameshwaramTemple: 'Rameshwaram Temple',
      satyanarayanaPooja: 'Satyanarayana Pooja',
      tirumalaTemple: 'Tirumala Temple',
      tirumala: 'Tirumala',
      lordVenkateswara: 'Lord Venkateswara',
      tirupati: 'Tirupati',
      rameshwaram: 'Rameshwaram',
      lordShiva: 'Lord Shiva',
      tamilNadu: 'Tamil Nadu',
      madurai: 'Madurai',
      goddessMeenakshi: 'Goddess Meenakshi',
      notificationLiveTitle: 'Live Pooja Starting Soon',
      notificationLiveMessage: 'Rudrabhishek at Sri Kalahasti starts in 2 hours',
      notificationLiveTime: '2h ago',
      notificationConfirmationTitle: 'Pooja Confirmed',
      notificationConfirmationMessage: 'Your Lakshmi Pooja has been scheduled for tomorrow',
      notificationConfirmationTime: '1 day ago',
      notificationFestivalTitle: 'Upcoming Festival',
      notificationFestivalMessage: 'Ekadashi is tomorrow - Book Vishnu poojas',
      notificationFestivalTime: '2 days ago',
    },
    categories: {
      abhishekam: 'Abhishekam',
      homam: 'Homam',
      archana: 'Archana',
      specialPoojas: 'Special Poojas',
      all: 'All Poojas',
    },
    poojas: {
      title: 'Sacred Poojas',
      subtitle: 'Discover authentic temple rituals',
      searchPlaceholder: 'Search poojas...',
      filters: 'Filters',
      noPoojas: 'No poojas found',
      liveStream: 'Live Stream Available',
      prasadIncluded: 'Prasad Included',
      duration: 'Duration',
      min: 'min',
    },
    poojaDetail: {
      overview: 'Overview',
      where: 'Where',
      how: 'How',
      why: 'Why',
      offerPooja: 'Offer This Pooja',
      sevaAmount: 'Seva Amount',
      duration: 'Duration',
      liveStreamAvailable: 'Live Stream Available',
      prasadIncluded: 'Prasad Included',
      whereTitle: 'Where this pooja is conducted',
      howTitle: 'How this pooja is conducted',
      whyTitle: 'Why devotees offer this pooja',
      suitableForRashi: 'Suitable for Rashi',
      blessings: 'Blessings',
      healthLongevity: 'Health and longevity',
      removalObstacles: 'Removal of obstacles',
      peaceMind: 'Peace of mind',
      sanskrit: 'Sanskrit',
      telugu: 'Telugu',
      pujariName: 'Pandit Ramesh Sharma',
      pujariInfo: '22 years experience • Telugu, Sanskrit',
      step1Name: 'Ganapathi Vandanam',
      step1Desc: 'Invoking Lord Ganesha to remove obstacles.',
      step2Name: 'Punyahavachanam',
      step2Desc: 'Purification of the space and devotee.',
      step3Name: 'Shivalinga Abhishekam',
      step3Desc: 'Sacred bath with water, milk, curd, honey and ghee.',
      step4Name: 'Bilvaarchana',
      step4Desc: 'Offering of 108 bilva leaves chanting each name of Shiva.',
      step5Name: 'Mangalarati',
      step5Desc: 'Concluding aarti with camphor and conch.',
      homamStep1Name: 'Ganapathi Pooja',
      homamStep1Desc: 'Prays to Lord Ganesha to ensure the fire ritual proceeds without obstacles.',
      homamStep2Name: 'Sankalpam',
      homamStep2Desc: 'Devotee names and family details are chanted to dedicate the homam intentions.',
      homamStep3Name: 'Agni Pratishta',
      homamStep3Desc: 'Consecration of the sacred fire altar and invoking the deity into the flame.',
      homamStep4Name: 'Homam Ahuti',
      homamStep4Desc: 'Sacred offerings of ghee, herbs, and samidha sticks while chanting mantras.',
      homamStep5Name: 'Purnaahuti & Aarti',
      homamStep5Desc: 'Final complete offering to seal the blessings followed by the sacred flame.',
      archanaStep1Name: 'Sankalpam',
      archanaStep1Desc: 'Declaration of the devotee\'s name, nakshatra, and gothram for dedicated prayers.',
      archanaStep2Name: 'Ashtottara Shatanamavali',
      archanaStep2Desc: 'Recitation of the 108 names of the deity while offering flowers or sacred leaves.',
      archanaStep3Name: 'Pushparchana',
      archanaStep3Desc: 'Chanting and showering fresh jasmine, marigold, and tulsi leaves onto the deity.',
      archanaStep4Name: 'Naivedyam',
      archanaStep4Desc: 'Offering of cooked rice, coconut, fruits, and sweets as sacred food to the lord.',
      archanaStep5Name: 'Mangalarati',
      archanaStep5Desc: 'Wave of the camphor flame to receive the final light and blessings.',
      specialStep1Name: 'Kalasa Pooja',
      specialStep1Desc: 'Invocation of the holy rivers and deities into the sacred water pot.',
      specialStep2Name: 'Pradhana Pooja',
      specialStep2Desc: 'Principal rituals, elaborate decorations, and direct offerings to the main deity.',
      specialStep3Name: 'Vrata Katha',
      specialStep3Desc: 'Reading and listening to the sacred story of the vratam, explaining its spiritual benefits.',
      specialStep4Name: 'Naivedyam & Prasadam',
      specialStep4Desc: 'Sacred food offering followed by packaging of the blessed items for distribution.',
      specialStep5Name: 'Mangalarati',
      specialStep5Desc: 'Concluding waving of the lamp signifying the end of the ceremony.',
      wealthProsperity: 'Wealth and prosperity',
      protectionNegative: 'Protection from negative energies',
      devotionGrace: 'Divine grace and devotion',
      wishFulfillment: 'Wish fulfillment',
      familyWellbeing: 'Family well-being',
      requirementsTitle: 'Requirements',
      requirementsDesc: 'All puja materials and offerings are arranged by the temple. Devotees do not need to provide anything.',
      notesTitle: 'Important Notes',
      notesDesc: 'The puja will be performed in your name and Gothram. Prasad delivery tracking will be updated under My Bookings tab within 24 hours of completion.',
      faqTitle: 'Pooja FAQs',
      faqQ1: 'Do I need to be present online?',
      faqA1: 'No. The priest will chant your Sankalpam. You can watch the live broadcast or the recording later.',
    },
    welcome: {
      tagline: 'Where Technology Meets Devotion',
      subtitle: 'Your sacred space for poojas, wherever you are.',
      continueMobile: 'Continue with Mobile',
      termsAgree: 'By continuing you agree to our Terms and Privacy Policy',
    },
    login: {
      brandSubtitle: 'Sacred poojas & ritual offerings',
      signInMobile: 'Sign In with Mobile',
      enterPhoneDesc: 'Enter your phone number to receive a one-time password (OTP).',
      enterPhonePlaceholder: 'Enter Mobile Number',
      errorPhone: 'Please enter a valid 10-digit mobile number',
      sendingOtp: 'Sending OTP...',
      sendOtp: 'Send OTP',
      verifyOtp: 'Verify OTP',
      otpSentDesc: "We've sent a 6-digit OTP to +91 {number}",
      enterOtpPlaceholder: 'Enter 6-Digit OTP',
      errorOtp: 'Please enter the 6-digit OTP',
      resendOtp: 'Resend OTP',
      verifying: 'Verifying...',
      verifyLogin: 'Verify & Login',
    },
    setup: {
      title: 'Which deities do you hold closest?',
      subtitle: 'We will personalise your pooja suggestions based on your answer.',
      skip: 'Skip for now',
    },
    live: {
      onBehalfOf: 'This Seva is being conducted on behalf of:',
      smooth: 'Smooth',
      devoteesJoined: '{count} Devotees Joined',
      guidance: '🙏 Chant along with the pujari if you know the mantras. Feel free to light a diya at your home temple during the Mangalarati.',
    },
    booking: {
      date1: '18 April 2026',
      date2: '22 April 2026',
      date3: '15 April 2026',
      stepInfo: 'Step {step} of 3',
      selectDateTime: 'Select Date & Time',
      yourDetails: 'Your Details',
      reviewConfirm: 'Review & Confirm',
      selectDate: 'Select Date',
      selectTime: 'Select Time',
      devoteeNames: 'Devotee Name(s)',
      devoteeNamesDesc: 'The pooja will be performed in these names',
      devoteeNamesPlaceholder: 'Enter names',
      gothram: 'Gothram',
      gothramPlaceholder: 'Enter Gothram',
      nakshatra: 'Nakshatra',
      nakshatraPlaceholder: 'Select Nakshatra',
      specialRequests: 'Special Requests',
      specialRequestsPlaceholder: 'Any specific prayers or intentions...',
      poojaDetails: 'Pooja Details',
      paymentSummary: 'Payment Summary',
      poojaAmount: 'Pooja Amount',
      prasadDelivery: 'Prasad Delivery',
      liveStream: 'Live Stream',
      totalAmount: 'Total Amount',
      proceedToPayment: 'Proceed to Payment',
      note: 'Note',
      confirmationNote: 'You will receive a confirmation with booking details and live stream link once payment is complete.',
      completePayment: 'Complete Seva Payment',
      sevaDetails: 'Seva Details',
      totalPrice: 'Total Seva Price',
      paidAdvance: 'Paid Amount (Advance)',
      remainingBalanceDue: 'Remaining Balance Due',
      payBalanceAmount: 'Pay Balance — ₹{amount}',
      processingOffering: 'Processing Sacred Offering...',
      processingDesc: 'Please do not close the app or press back. We are connecting to the temple secure gateway.',
      paymentSuccess: 'Payment Successful! 🙏',
      confirmSuccess: "Your seva '{title}' is now fully confirmed.",
      sankalpamNote: 'The temple priest will chant the sankalpam in your name. Prasad delivery tracking details will update shortly.',
    },
    bookingConfirmation: {
      title: 'Your Seva Has Been Offered',
      subtitle: 'The pooja will be performed in your name and Gothram. May the blessings be with you and your family.',
      bookingConfirmed: 'Booking Confirmed',
      bookingId: 'Booking ID',
      viewJourney: 'View Full Journey',
      backToHome: 'Back to Home',
      setReminder: 'Set Reminder',
      shareBlessing: 'Share Blessing',
    },
    bookings: {
      title: 'My Bookings',
      subtitle: 'Track your pooja journey',
      active: 'Active',
      completed: 'Completed',
      noActive: 'No active bookings',
      noCompleted: 'No completed bookings',
      noActiveDesc: 'Book your first pooja to get started',
      noCompletedDesc: 'Your completed poojas will appear here',
      viewJourney: 'View Full Journey',
      watchRecording: 'Watch Recording',
      trackPrasad: 'Track Prasad',
      poojaJourney: 'Pooja Journey',
    },
    journey: {
      title: 'Pooja Journey',
      sevaOffered: 'Seva Offered',
      pujariAssigned: 'Pujari Assigned',
      confirmed: 'Confirmed',
      poojaScheduled: 'Scheduled',
      goingLive: 'Pooja Live',
      poojaCompleted: 'Completed',
      recordingReady: 'Recording Ready',
      prasadPacked: 'Prasad Packed',
      prasadDispatched: 'Dispatched',
      prasadDelivered: 'Delivered',
      sankalpamDetails: 'Sankalpam Details',
      poojaSeva: 'Pooja Seva',
      templeLocation: 'Temple Location',
      devoteeName: 'Devotee Name',
      gothramNakshatra: 'Gothram / Nakshatra',
      watchBroadcast: 'Watch Video Broadcast',
      trackPrasad: 'Track Prasad Box',
      sevaOfferedDesc: 'Your ritual request has been received with devotion.',
      pujariAssignedDesc: 'Pandit Ramesh Sharma has been assigned to conduct your seva.',
      poojaScheduledDesc: 'Sankalpam timed for 15 April at 9:00 AM IST.',
      goingLiveDesc: 'Sacred live stream was broadcasted. Blessings shared.',
      poojaCompletedDesc: 'Pooja performed successfully in your name and Gothram.',
      recordingReadyDesc: 'Your dedicated pooja video archive is preparing.',
      prasadPackedDesc: 'Sacred elements packaged in the Devaseva blessing box.',
      prasadDispatchedDesc: 'Your Prasad is on the way. Tracking details pending.',
      prasadDeliveredDesc: 'May the sacred offerings bring peace to your home.',
    },
    temples: {
      title: 'Sacred Temples',
      subtitle: 'Explore divine temples',
      explore: 'Explore',
      hide: 'Hide',
      availablePoojas: 'Available Poojas',
      location: 'Location',
    },
    profile: {
      title: 'Profile',
      personalisation: 'Personalisation',
      aiRecommendations: 'Your Sacred Recommendations',
      settings: 'Settings',
      theme: 'Theme',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      notifications: 'Notifications',
      hinduCalendar: 'Hindu Calendar',
      helpSupport: 'Help & Support',
      appSettings: 'App Settings',
      signOut: 'Sign Out',
      version: 'Made with devotion',
      editProfile: 'Edit Profile',
      editPersonalInfo: 'Edit Personal Information',
      fullName: 'Full Name',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
      nakshatra: 'Nakshatra',
      rashi: 'Rashi',
      dateOfBirth: 'Date of Birth',
      gothram: 'Gothram',
      saveChanges: 'Save Changes',
      recommendationsTitle: 'Based on Your Nakshatra',
      recommendationsDesc: 'Personalised pooja recommendations just for you',
      viewRecommendations: 'View Recommendations',
      totalPoojas: 'Poojas',
      upcomingCount: 'Upcoming',
      devotionScore: 'Devotion',
      ishtaDevatas: 'Ishta Devatas (Deity Preferences)',
      noDeities: 'No deities selected yet',
      selectIshtaDevatas: 'Select Ishta Devatas',
      savePreferences: 'Save Preferences',
      val: {
        priya: 'Priya',
        raghavan: 'Raghavan Iyer',
        bangalore: 'Bangalore, Karnataka',
        shravana: 'Shravana',
        makara: 'Makara (Capricorn)',
        dob: 'Jan 15, 1990',
        bharadwaja: 'Bharadwaja'
      }
    },
    notifications: {
      title: 'Notification Settings',
      poojaReminders: 'Pooja Reminders',
      poojaRemindersDesc: 'Get reminded before your scheduled poojas',
      liveStreams: 'Live Streams',
      liveStreamsDesc: 'Notification when your pooja starts streaming',
      prasadUpdates: 'Prasad Updates',
      prasadUpdatesDesc: 'Track your prasad delivery status',
      festivalAlerts: 'Festival Alerts',
      festivalAlertsDesc: 'Special poojas and festival notifications',
      saveSettings: 'Save Settings',
    },
    calendar: {
      title: 'Hindu Calendar',
      todayTithi: "Today's Tithi",
      upcomingFestivals: 'Upcoming Festivals',
      shuklaPakshaChaturthi: 'Shukla Paksha Chaturthi',
      recommendedPoojas: 'Recommended Poojas',
      offerSeva: 'Offer Seva',
      legendFestival: 'Festival',
      legendEkadashi: 'Ekadashi',
      legendAmavasya: 'Amavasya',
      legendPournami: 'Pournami',
      eventUgadiTitle: '14 April — Ugadi (Telugu New Year)',
      eventUgadiDesc: 'Telugu & Kannada New Year. A deeply auspicious day for new beginnings, buying assets, and offering special prayers.',
      eventRamNavamiTitle: '17 April — Sri Ram Navami',
      eventRamNavamiDesc: 'Birth anniversary of Lord Rama. Ideal for peace, purification of the mind, and chanting holy names.',
      eventAmavasyaTitle: '18 April — Amavasya',
      eventAmavasyaDesc: 'New Moon day. A highly powerful time for ancestral blessings, releasing negative karma, and performing cleansing homams.',
      eventPournamiTitle: '3 April — Pournami',
      eventPournamiDesc: 'Full Moon day. Auspicious for receiving divine energy, meditation, and Satyanarayana Vratam for family prosperity.',
      eventEkadashiTitle: '{day} April — Ekadashi',
      eventEkadashiDesc: 'A sacred day dedicated to Lord Vishnu. Highly beneficial for fasting, mental clarity, and spiritual progress.',
      dayTitle: '{day} April',
      dayDesc: 'An auspicious day for daily prayers, meditation, and offering sacred archana at temples.',
      april: 'April',
      weekday0: 'S',
      weekday1: 'M',
      weekday2: 'T',
      weekday3: 'W',
      weekday4: 'T',
      weekday5: 'F',
      weekday6: 'S',
    },
    festival: {
      ugadi: 'Ugadi',
      ugadiDesc: 'Telugu & Kannada New Year',
      ramNavami: 'Sri Ram Navami',
      ramNavamiDesc: 'Birth of Lord Rama',
      vishu: 'Vishu',
      vishuDesc: 'Malayalam New Year',
      hanumanJayanti: 'Hanuman Jayanti',
      hanumanJayantiDesc: 'Birth of Lord Hanuman',
    },
    help: {
      title: 'Help & Support',
      contactSupport: 'Contact Support',
      faq: 'Frequently Asked Questions',
      faq1Q: 'How do I book a pooja?',
      faq1A: "Browse poojas, select your preferred temple and time, then click 'Offer This Pooja' to complete your booking.",
      faq2Q: 'Can I watch the pooja live?',
      faq2A: "Yes! When your pooja begins, you'll receive a notification. Click 'View Live' in your bookings to watch in real-time.",
      faq3Q: 'How is prasad delivered?',
      faq3A: 'After your pooja is completed, prasad is carefully packed and shipped to your address.',
    },
    language: {
      label: 'Language',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
    deity: {
      ganesha: 'Ganesha',
      lakshmi: 'Lakshmi',
      shiva: 'Shiva',
      vishnu: 'Vishnu',
      durga: 'Durga',
      saraswati: 'Saraswati',
      hanuman: 'Hanuman',
      murugan: 'Murugan',
    },
    poojaDb: {
      1: { title: 'Rudrabhishekam', purpose: 'Sacred bathing ritual for Lord Shiva for spiritual purification' },
      2: { title: 'Vishnu Abhishekam', purpose: 'Divine bathing ceremony for Lord Vishnu for prosperity and peace' },
      3: { title: 'Lakshmi Abhishekam', purpose: 'Sacred bathing ritual for Goddess Lakshmi to attract wealth' },
      4: { title: 'Ganesha Abhishekam', purpose: 'Remove obstacles and invoke blessings for new beginnings' },
      5: { title: 'Saraswati Abhishekam', purpose: 'Enhance knowledge, wisdom, and artistic abilities' },
      6: { title: 'Ganapathi Homam', purpose: 'Fire ritual to remove obstacles and ensure success in endeavors' },
      7: { title: 'Navagraha Homam', purpose: 'Balances planetary influences and removes doshas' },
      8: { title: 'Lakshmi Kubera Homam', purpose: 'Attracts wealth, prosperity, and financial abundance' },
      9: { title: 'Sudarshana Homam', purpose: 'Protection from negative energies and evil forces' },
      10: { title: 'Maha Mrityunjaya Homam', purpose: 'Promotes health, longevity, and victory over death' },
      11: { title: 'Sahasranama Archana', purpose: 'Chanting 1000 names of Lord Vishnu for divine blessings' },
      12: { title: 'Lalita Sahasranama Archana', purpose: 'Invoke divine feminine energy and blessings' },
      13: { title: 'Ashtottara Shatanamavali', purpose: 'Offering 108 names for quick blessings and obstacle removal' },
      14: { title: 'Hanuman Chalisa Archana', purpose: 'Gain strength, courage, and protection from difficulties' },
      15: { title: 'Durga Ashtottara Archana', purpose: 'Divine mother\'s blessings for protection and strength' },
      16: { title: 'Satyanarayana Vratam', purpose: 'Complete vratam for fulfillment of wishes and prosperity' },
      17: { title: 'Varalakshmi Vratam', purpose: 'Special vratam for family well-being and abundance' },
      18: { title: 'Kalasabhishekam', purpose: 'Grand abhishekam with sacred pots for complete purification' },
      19: { title: 'Pradosham Special Pooja', purpose: 'Performed during pradosham time for liberation from sins' },
      20: { title: 'Ekadashi Special Pooja', purpose: 'Auspicious pooja on Ekadashi for spiritual elevation' }
    },
    templeDb: {
      tirumala: { name: 'Tirumala Temple', location: 'Andhra Pradesh', deity: 'Lord Venkateswara', description: 'One of the richest and most visited pilgrimage centers in the world' },
      rameshwaram: { name: 'Rameshwaram Temple', location: 'Tamil Nadu', deity: 'Lord Shiva', description: 'Sacred Jyotirlinga temple on the island of Rameshwaram' },
      madurai: { name: 'Madurai Temple', location: 'Tamil Nadu', deity: 'Goddess Meenakshi', description: 'Historic temple dedicated to Goddess Parvati in the form of Meenakshi' },
      varanasi: { name: 'Varanasi Temple', location: 'Uttar Pradesh', deity: 'Lord Shiva', description: 'Ancient temple on the banks of the holy Ganges river' },
      siddhiVinayak: { name: 'Siddhi Vinayak Temple', location: 'Maharashtra', deity: 'Lord Ganesha', description: 'Famous temple dedicated to Lord Ganesha in Mumbai' }
    }
  },
  te: {
    common: {
      search: 'పూజలను వెతకండి...',
      viewAll: 'అన్నీ చూడండి',
      upcoming: 'రాబోయే',
      active: 'క్రియాశీల',
      completed: 'పూర్తయింది',
      cancel: 'రద్దు చేయండి',
      save: 'భద్రపరచండి',
      continue: 'కొనసాగించండి',
      back: 'వెనుకకు',
      edit: 'సవరించండి',
      signOut: 'సైన్ అవుట్',
      close: 'మూసివేయండి',
      viewDetails: 'వివరాలు చూడండి',
      bookNow: 'ఇప్పుడే బుక్ చేయండి',
      free: 'ఉచితం',
      included: 'చేర్చబడింది',
      clearAll: 'అన్ని తుడించండి',
      signIn: 'Sign In',
      offerSeva: 'సేవ సమర్పించండి',
      tomorrow: 'రేపు',
      optional: 'ఐచ్ఛికం',
    },
    nav: {
      home: 'హోమ్',
      poojas: 'పూజలు',
      bookings: 'బుకింగ్‌లు',
      temples: 'ఆలయాలు',
      profile: 'ప్రొఫైల్',
    },
    home: {
      greeting: 'నమస్తే',
      subtitle: 'ఈరోజు ఏకాదశి — విష్ణు పూజలకు శుభ దినం.',
      featuredTemples: 'ప్రముఖ ఆలయాలు',
      categories: 'పూజా వర్గాలు',
      upcomingPoojas: 'రాబోయే పూజలు',
      notifications: 'నోటిఫికేషన్‌లు',
      noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
      viewNotification: 'చూడండి',
      recommendedForYou: 'మీ కోసం సిఫార్సు చేయబడింది',
      basedOnNakshatra: 'మీ నక్షత్రం ఆధారంగా',
      nextLivePooja: 'తదుపరి లైవ్ పూజ',
      nextLivePoojaName: 'శ్రీకాళహస్తిలో రుద్రాభిషేకం',
      offerSevaAmount: 'సేవ సమర్పించండి — ₹1,100',
      upcoming: 'రాబోయేది',
      temples: 'ఆలయాలు',
      forYou: 'మీ కోసం',
      live: 'లైవ్',
      poojasCount: '{count} పూజలు',
      today: 'నేడు',
      ekadashi: 'ఏకాదశి',
      purnima: 'పూర్ణిమ',
      wed: 'బుధ',
      thu: 'గురు',
      fri: 'శుక్ర',
      sat: 'శని',
      sun: 'ఆది',
      mon: 'సోమ',
      tue: 'మంగళ',
      lakshmiPooja: 'లక్ష్మీ పూజ',
      maduraiTemple: 'మదురై ఆలయం',
      rameshwaramTemple: 'రామేశ్వరం ఆలయం',
      satyanarayanaPooja: 'సత్యనారాయణ పూజ',
      tirumalaTemple: 'తిరుమల ఆలయం',
      tirumala: 'తిరుమల',
      lordVenkateswara: 'వెంకటేశ్వర స్వామి',
      tirupati: 'తిరుపతి',
      rameshwaram: 'రామేశ్వరం',
      lordShiva: 'శివుడు',
      tamilNadu: 'తమిళనాడు',
      madurai: 'మదురై',
      goddessMeenakshi: 'మీనాక్షి అమ్మవారు',
      notificationLiveTitle: 'లైవ్ పూజ త్వరలో ప్రారంభం కానుంది',
      notificationLiveMessage: 'శ్రీకాళహస్తిలో రుద్రాభిషేకం 2 గంటల్లో ప్రారంభమవుతుంది',
      notificationLiveTime: '2గం క్రితం',
      notificationConfirmationTitle: 'పూజ నిర్ధారించబడింది',
      notificationConfirmationMessage: 'మీ లక్ష్మీ పూజ రేపటికి షెడ్యూల్ చేయబడింది',
      notificationConfirmationTime: '1 రోజు క్రితం',
      notificationFestivalTitle: 'రాబోయే పండుగ',
      notificationFestivalMessage: 'రేపు ఏకాదశి - విష్ణు పూజలను బుక్ చేసుకోండి',
      notificationFestivalTime: '2 రోజుల క్రితం',
    },
    categories: {
      abhishekam: 'అభిషేకం',
      homam: 'హోమం',
      archana: 'అర్చన',
      specialPoojas: 'ప్రత్యేక పూజలు',
      all: 'అన్ని పూజలు',
    },
    poojas: {
      title: 'పవిత్ర పూజలు',
      subtitle: 'ప్రామాణికమైన ఆలయ ఆచారాలను కనుగొనండి',
      searchPlaceholder: 'పూజలను వెతకండి...',
      filters: 'ఫిల్టర్‌లు',
      noPoojas: 'పూజలు కనుగొనబడలేదు',
      liveStream: 'లైవ్ స్ట్రీమ్ అందుబాటులో ఉంది',
      prasadIncluded: 'ప్రసాదం చేర్చబడింది',
      duration: 'వ్యవధి',
      min: 'నిమి',
    },
    poojaDetail: {
      overview: 'అవలోకనం',
      where: 'ఎక్కడ',
      how: 'ఎలా',
      why: 'ఎందుకు',
      offerPooja: 'ఈ పూజను సమర్పించండి',
      sevaAmount: 'సేవా మొత్తం',
      duration: 'వ్యవధి',
      liveStreamAvailable: 'లైవ్ స్ట్రీమ్ అందుబాటులో ఉంది',
      prasadIncluded: 'ప్రసాదం చేర్చబడింది',
      whereTitle: 'ఈ పూజ ఎక్కడ నిర్వహించబడుతుంది',
      howTitle: 'ఈ పూజ ఎలా నిర్వహించబడుతుంది',
      whyTitle: 'భక్తులు ఈ పూజను ఎందుకు సమర్పిస్తారు',
      suitableForRashi: 'రాశికి అనుకూలమైనది',
      blessings: 'ఆశీర్వాదాలు',
      healthLongevity: 'ఆరోగ్యం మరియు దీర్ఘాయువు',
      removalObstacles: 'ఆటంకాల తొలగింపు',
      peaceMind: 'మనశ్శాంతి',
      sanskrit: 'సంస్కృతం',
      telugu: 'తెలుగు',
      pujariName: 'పండిట్ రమేష్ శర్మ',
      pujariInfo: '22 సంవత్సరాల అనుభవం • తెలుగు, సంస్కృతం',
      step1Name: 'గణపతి వందనం',
      step1Desc: 'ఆటంకాలను తొలగించడానికి వినాయకుడిని ప్రార్థించడం.',
      step2Name: 'పుణ్యాహవాచనం',
      step2Desc: 'పూజా స్థలం మరియు భక్తుడి శుద్ధీకరణ.',
      step3Name: 'శివలింగ అభిషేకం',
      step3Desc: 'నీరు, పాలు, పెరుగు, తేనె మరియు నెయ్యిలతో పవిత్ర స్నాన సమర్పణ.',
      step4Name: 'బిల్వార్చన',
      step4Desc: 'శివుని ప్రతి నామమును ఉచ్చరిస్తూ 108 బిల్వ పత్రాలను సమర్పించడం.',
      step5Name: 'మంగళహారతి',
      step5Desc: 'కర్పూరం మరియు శంఖంతో పూజ ముగింపు హారతి.',
      homamStep1Name: 'గణపతి పూజ',
      homamStep1Desc: 'యాగం ఎలాంటి ఆటంకాలు లేకుండా సాగాలని వినాయకుడిని ప్రార్థించడం.',
      homamStep2Name: 'సంకల్పం',
      homamStep2Desc: 'భక్తుల పేర్లు, నక్షత్రాలు, గోత్రాలతో యాగ సంకల్పం చేయడం.',
      homamStep3Name: 'అగ్ని ప్రతిష్ట',
      homamStep3Desc: 'పవిత్ర హోమ గుండాన్ని సిద్ధం చేసి అగ్ని దేవుడిని ఆహ్వానించడం.',
      homamStep4Name: 'హోమ ఆహుతి',
      homamStep4Desc: 'మంత్రోచ్ఛారణల మధ్య నెయ్యి, మూలికలు మరియు సమిధలను సమర్పించడం.',
      homamStep5Name: 'పూర్ణాహుతి & హారతి',
      homamStep5Desc: 'యాగ సమాప్తి సూచకంగా పూర్ణాహుతి సమర్పించి హారతి ఇవ్వడం.',
      archanaStep1Name: 'సంకల్పం',
      archanaStep1Desc: 'భక్తుని పేరు, నక్షత్రం మరియు గోత్రాలను పఠించి ప్రార్థించడం.',
      archanaStep2Name: 'అష్టోత్తర శతనామావళి',
      archanaStep2Desc: 'దేవతా మూర్తి యొక్క 108 నామాలను పఠిస్తూ పూలు లేదా పత్రాలను సమర్పించడం.',
      archanaStep3Name: 'పుష్పార్చన',
      archanaStep3Desc: 'తాజా పూలతో దేవతా మూర్తికి అర్చన సమర్పించడం.',
      archanaStep4Name: 'నైవేద్యం',
      archanaStep4Desc: 'కొబ్బరికాయ, పండ్లు, పిండి వంటలను దేవునికి సమర్పించడం.',
      archanaStep5Name: 'మంగళహారతి',
      archanaStep5Desc: 'కర్పూర జ్యోతిని వెలిగించి దేవతా మూర్తికి హారతి ఇవ్వడం.',
      specialStep1Name: 'కలశ పూజ',
      specialStep1Desc: 'పవిత్ర నదులను మరియు దేవతలను కలశ తీర్థంలోకి ఆహ్వానించడం.',
      specialStep2Name: 'ప్రధాన పూజ',
      specialStep2Desc: 'దేవతా మూర్తికి షోడశోపచార పూజలు, అలంకరణలు మరియు సమర్పణలు చేయడం.',
      specialStep3Name: 'వ్రత కథ',
      specialStep3Desc: 'వ్రతానికి సంబంధించిన పవిత్ర కథను పఠించి, దాని ప్రాముఖ్యతను తెలుసుకోవడం.',
      specialStep4Name: 'నైవేద్యం & ప్రసాదం',
      specialStep4Desc: 'పవిత్ర భోజన సమర్పణ మరియు భక్తులకు పంచడానికి ప్రసాదాన్ని సిద్ధం చేయడం.',
      specialStep5Name: 'మంగళహారతి',
      specialStep5Desc: 'పూజ ముగింపు సందర్భంగా హారతి సమర్పించడం.',
      wealthProsperity: 'సంపద మరియు ఐశ్వర్యం',
      protectionNegative: 'నకారాత్మక శక్తుల నుండి రక్షణ',
      devotionGrace: 'దైవిక అనుగ్రహం మరియు భక్తి',
      wishFulfillment: 'కోరికల నెరవేర్పు',
      familyWellbeing: 'కుటుంబ క్షేమం',
      requirementsTitle: 'కావలసిన సామగ్రి',
      requirementsDesc: 'పూజా సామాగ్రి మరియు సమర్పణలన్నీ ఆలయం ద్వారా ఏర్పాటు చేయబడతాయి. భక్తులు ఏమీ పంపవలసిన అవసరం లేదు.',
      notesTitle: 'ముఖ్యమైన గమనికలు',
      notesDesc: 'పూజ మీ పేరు మరియు గోత్రంతో నిర్వహించబడుతుంది. పూజ పూర్తయిన 24 గంటల్లో ప్రసాద రవాణా వివరాలు బుకింగ్స్ ట్యాబ్‌లో నవీకరించబడతాయి.',
      faqTitle: 'పూజా ప్రశ్నలు',
      faqQ1: 'నేను ఆన్‌లైన్‌లో ఉండాలా?',
      faqA1: 'అవసరం లేదు. పూజారి మీ సంకల్పం పఠిస్తారు. మీరు ప్రత్యక్ష ప్రసారం లేదా రికార్డింగ్‌ను తర్వాత చూడవచ్చు.',
    },
    welcome: {
      tagline: 'సాంకేతికత భక్తిని కలిసే చోటు',
      subtitle: 'మీరు ఎక్కడ ఉన్నా, పూజల కొరకు మీ పవిత్ర స్థలం.',
      continueMobile: 'మొబైల్‌తో కొనసాగండి',
      termsAgree: 'కొనసాగడం ద్వారా మీరు మా నిబంధనలు మరియు గోప్యతా విధానానికి అంగీకరిస్తున్నారు',
    },
    login: {
      brandSubtitle: 'పవిత్ర పూజలు & సాంప్రదాయ సమర్పణలు',
      signInMobile: 'మొబైల్‌తో సైన్ ఇన్',
      enterPhoneDesc: 'వన్-టైమ్ పాస్‌వర్డ్ (OTP) పొందడానికి మీ ఫోన్ నంబర్‌ను నమోదు చేయండి.',
      enterPhonePlaceholder: 'మొబైల్ నంబర్ నమోదు చేయండి',
      errorPhone: 'దయచేసి సరైన 10-అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
      sendingOtp: 'OTP పంపుతోంది...',
      sendOtp: 'OTP పంపండి',
      verifyOtp: 'OTP వెరిఫై చేయండి',
      otpSentDesc: "మేము +91 {number} నంబర్‌కు 6-అంకెల OTPని పంపాము",
      enterOtpPlaceholder: '6-అంకెల OTP నమోదు చేయండి',
      errorOtp: 'దయచేసి 6-అంకెల OTPని నమోదు చేయండి',
      resendOtp: 'మళ్లీ OTP పంపండి',
      verifying: 'వెరిఫై చేస్తోంది...',
      verifyLogin: 'వెరిఫై & లాగిన్',
    },
    setup: {
      title: 'మీకు అత్యంత సన్నిహితమైన దేవతలు ఎవరు?',
      subtitle: 'మీ సమాధానం ఆధారంగా మేము మీ పూజా సూచనలను వ్యక్తిగతీకరిస్తాము.',
      skip: 'ఇప్పుడే వద్దు',
    },
    live: {
      onBehalfOf: 'ఈ సేవ వీరి తరపున నిర్వహించబడుతోంది:',
      smooth: 'సులభం',
      devoteesJoined: '{count} భక్తులు పాల్గొన్నారు',
      guidance: '🙏 మీకు మంత్రాలు తెలిస్తే పూజారితో కలిసి జపించండి. మంగళహారతి సమయంలో మీ ఇంటి ఆలయంలో దీపం వెలిగించవచ్చు.',
    },
    booking: {
      date1: '18 ఏప్రిల్ 2026',
      date2: '22 ఏప్రిల్ 2026',
      date3: '15 ఏప్రిల్ 2026',
      stepInfo: 'దశ {step}/3',
      selectDateTime: 'తేదీ మరియు సమయాన్ని ఎంచుకోండి',
      yourDetails: 'మీ వివరాలు',
      reviewConfirm: 'సమీక్షించండి మరియు నిర్ధారించండి',
      selectDate: 'తేదీని ఎంచుకోండి',
      selectTime: 'సమయాన్ని ఎంచుకోండి',
      devoteeNames: 'భక్తుల పేర్లు',
      devoteeNamesDesc: 'ఈ పేర్లలో పూజ నిర్వహించబడుతుంది',
      devoteeNamesPlaceholder: 'పేర్లు నమోదు చేయండి',
      gothram: 'గోత్రం',
      gothramPlaceholder: 'గోత్రం నమోదు చేయండి',
      nakshatra: 'నక్షత్రం',
      nakshatraPlaceholder: 'నక్షత్రం ఎంచుకోండి',
      specialRequests: 'ప్రత్యేక అభ్యర్థనలు',
      specialRequestsPlaceholder: 'ఏదైనా నిర్దిష్ట ప్రార్థనలు లేదా ఉద్దేశాలు...',
      poojaDetails: 'పూజా వివరాలు',
      paymentSummary: 'చెల్లింపు సారాంశం',
      poojaAmount: 'పూజా మొత్తం',
      prasadDelivery: 'ప్రసాదం డెలివరీ',
      liveStream: 'లైవ్ స్ట్రీమ్',
      totalAmount: 'మొత్తం మొత్తం',
      proceedToPayment: 'చెల్లింపుకు కొనసాగండి',
      note: 'గమనిక',
      confirmationNote: 'చెల్లింపు పూర్తయిన తర్వాత మీరు బుకింగ్ వివరాలు మరియు లైవ్ స్ట్రీమ్ లింక్‌తో నిర్ధారణను అందుకుంటారు.',
      completePayment: 'సేవా చెల్లింపును పూర్తి చేయండి',
      sevaDetails: 'సేవా వివరాలు',
      totalPrice: 'మొత్తం సేవా ధర',
      paidAdvance: 'చెల్లించిన మొత్తం (అడ్వాన్స్)',
      remainingBalanceDue: 'చెల్లించాల్సిన మిగిలిన బ్యాలెన్స్',
      payBalanceAmount: 'బ్యాలెన్స్ చెల్లించండి — ₹{amount}',
      processingOffering: 'పవిత్ర సమర్పణను ప్రాసెస్ చేస్తోంది...',
      processingDesc: 'దయచేసి యాప్‌ను మూసివేయవద్దు లేదా వెనుకకు వెళ్ళవద్దు. మేము ఆలయ సురక్షిత గేట్‌వేకి కనెక్ట్ అవుతున్నాము.',
      paymentSuccess: 'చెల్లింపు విజయవంతమైంది! 🙏',
      confirmSuccess: "మీ సేవ '{title}' ఇప్పుడు పూర్తిగా నిర్ధారించబడింది.",
      sankalpamNote: 'ఆలయ పూజారి మీ పేరు మీద సంకల్పం జపిస్తారు. ప్రసాదం డెలివరీ ట్రాకింగ్ వివరాలు త్వరలో నవీకరించబడతాయి.',
    },
    bookingConfirmation: {
      title: 'మీ సేవ సమర్పించబడింది',
      subtitle: 'మీ పేరు మరియు గోత్రంలో పూజ నిర్వహించబడుతుంది. మీకు మరియు మీ కుటుంబానికి ఆశీర్వాదాలు ఉండాలి.',
      bookingConfirmed: 'బుకింగ్ నిర్ధారించబడింది',
      bookingId: 'బుకింగ్ ఐడి',
      viewJourney: 'పూర్తి ప్రయాణాన్ని చూడండి',
      backToHome: 'హోమ్‌కు తిరిగి వెళ్ళండి',
      setReminder: 'రిమైండర్ సెట్ చేయండి',
      shareBlessing: 'ఆశీస్సులను పంచుకోండి',
    },
    bookings: {
      title: 'నా బుకింగ్‌లు',
      subtitle: 'మీ పూజా ప్రయాణాన్ని ట్రాక్ చేయండి',
      active: 'క్రియాశీల',
      completed: 'పూర్తయింది',
      noActive: 'క్రియాశీల బుకింగ్‌లు లేవు',
      noCompleted: 'పూర్తయిన బుకింగ్‌లు లేవు',
      noActiveDesc: 'మీ మొదటి పూజను బుక్ చేయండి',
      noCompletedDesc: 'పూర్తయిన పూజలు ఇక్కడ కనిపిస్తాయి',
      viewJourney: 'పూర్తి ప్రయాణాన్ని చూడండి',
      watchRecording: 'రికార్డింగ్ చూడండి',
      trackPrasad: 'ప్రసాదాన్ని ట్రాక్ చేయండి',
      poojaJourney: 'పూజా ప్రయాణం',
    },
    journey: {
      title: 'పూజా ప్రయాణం',
      sevaOffered: 'సేవ సమర్పించబడింది',
      pujariAssigned: 'పూజారి నియమించబడ్డారు',
      confirmed: 'నిర్ధారించబడింది',
      poojaScheduled: 'షెడ్యూల్ చేయబడింది',
      goingLive: 'పూజ లైవ్',
      poojaCompleted: 'పూర్తయింది',
      recordingReady: 'రికార్డింగ్ సిద్ధంగా ఉంది',
      prasadPacked: 'ప్రసాదం ప్యాక్ చేయబడింది',
      prasadDispatched: 'పంపబడింది',
      prasadDelivered: 'డెలివరీ చేయబడింది',
      sankalpamDetails: 'సంకల్పం వివరాలు',
      poojaSeva: 'పూజా సేవ',
      templeLocation: 'ఆలయ స్థలం',
      devoteeName: 'భక్తుని పేరు',
      gothramNakshatra: 'గోత్రం / నక్షత్రం',
      watchBroadcast: 'వీడియో ప్రసారాన్ని చూడండి',
      trackPrasad: 'ప్రసాదం బాక్స్‌ను ట్రాక్ చేయండి',
      sevaOfferedDesc: 'మీ పూజా అభ్యర్థన భక్తితో స్వీకరించబడింది.',
      pujariAssignedDesc: 'మీ సేవను నిర్వహించడానికి పండిట్ రమేష్ శర్మ నియమించబడ్డారు.',
      poojaScheduledDesc: 'సంకల్పం 15 ఏప్రిల్ ఉదయం 9:00 గంటలకు నిర్ణయించబడింది.',
      goingLiveDesc: 'పవిత్ర ప్రత్యక్ష ప్రసారం ప్రసారం చేయబడింది. ఆశీస్సులు పంచుకోబడ్డాయి.',
      poojaCompletedDesc: 'మీ పేరు మరియు గోత్రంలో పూజా సేవ విజయవంతంగా నిర్వహించబడింది.',
      recordingReadyDesc: 'మీ పూజా వీడియో ఆర్కైవ్ సిద్ధమవుతోంది.',
      prasadPackedDesc: 'పవిత్ర వస్తువులు దేవసేవ ఆశీస్సుల బాక్స్‌లో ప్యాక్ చేయబడ్డాయి.',
      prasadDispatchedDesc: 'మీ ప్రసాదం దారిలో ఉంది. ట్రాకింగ్ వివరాలు రావాల్సి ఉంది.',
      prasadDeliveredDesc: 'పవిత్ర ప్రసాదం మీ ఇంట శాంతిని చేకూర్చుగాక.',
    },
    temples: {
      title: 'పవిత్ర ఆలయాలు',
      subtitle: 'దివ్య ఆలయాలను అన్వేషించండి',
      explore: 'అన్వేషించండి',
      hide: 'దాచండి',
      availablePoojas: 'అందుబాటులో ఉన్న పూజలు',
      location: 'స్థానం',
    },
    profile: {
      title: 'ప్రొఫైల్',
      personalisation: 'వ్యక్తిగతీకరణ',
      aiRecommendations: 'మీ పవిత్ర సిఫార్సులు',
      settings: 'సెట్టింగ్‌లు',
      theme: 'థీమ్',
      darkMode: 'డార్క్ మోడ్',
      lightMode: 'లైట్ మోడ్',
      notifications: 'నోటిఫికేషన్‌లు',
      hinduCalendar: 'హిందూ క్యాలెండర్',
      helpSupport: 'సహాయం & మద్దతు',
      appSettings: 'యాప్ సెట్టింగ్‌లు',
      signOut: 'సైన్ అవుట్',
      version: 'భక్తితో తయారు చేయబడింది',
      editProfile: 'ప్రొఫైల్‌ను సవరించండి',
      editPersonalInfo: 'వ్యక్తిగత సమాచారాన్ని సవరించండి',
      fullName: 'పూర్తి పేరు',
      email: 'ఇమెయిల్',
      phone: 'ఫోన్',
      location: 'స్థానం',
      nakshatra: 'నక్షత్రం',
      rashi: 'రాశి',
      dateOfBirth: 'పుట్టిన తేదీ',
      gothram: 'గోత్రం',
      saveChanges: 'మార్పులను భద్రపరచండి',
      recommendationsTitle: 'మీ నక్షత్రం ఆధారంగా',
      recommendationsDesc: 'మీ కోసం వ్యక్తిగతీకరించిన పూజా సిఫార్సులు',
      viewRecommendations: 'సిఫార్సులను చూడండి',
      totalPoojas: 'పూజలు',
      upcomingCount: 'రాబోయేవి',
      devotionScore: 'భక్తి',
      ishtaDevatas: 'ఇష్ట దేవతలు (దైవ ప్రాధాన్యతలు)',
      noDeities: 'ఇంకా ఏ దేవతలను ఎంచుకోలేదు',
      selectIshtaDevatas: 'ఇష్ట దేవతలను ఎంచుకోండి',
      savePreferences: 'ప్రాధాన్యతలను భద్రపరచండి',
      val: {
        priya: 'ప్రియ',
        raghavan: 'రాఘవన్ అయ్యర్',
        bangalore: 'బెంగళూరు, కర్ణాటక',
        shravana: 'శ్రవణ',
        makara: 'మకరం (మకర రాశి)',
        dob: 'జనవరి 15, 1990',
        bharadwaja: 'భరద్వాజ'
      }
    },
    notifications: {
      title: 'నోటిఫికేషన్ సెట్టింగ్‌లు',
      poojaReminders: 'పూజా రిమైండర్‌లు',
      poojaRemindersDesc: 'మీ షెడ్యూల్ చేసిన పూజలకు ముందు రిమైండర్ పొందండి',
      liveStreams: 'లైవ్ స్ట్రీమ్‌లు',
      liveStreamsDesc: 'మీ పూజ స్ట్రీమింగ్ ప్రారంభమైనప్పుడు నోటిఫికేషన్',
      prasadUpdates: 'ప్రసాదం నవీకరణలు',
      prasadUpdatesDesc: 'మీ ప్రసాదం డెలివరీ స్థితిని ట్రాక్ చేయండి',
      festivalAlerts: 'పండుగ హెచ్చరికలు',
      festivalAlertsDesc: 'ప్రత్యేక పూజలు మరియు పండుగ నోటిఫికేషన్‌లు',
      saveSettings: 'సెట్టింగ్‌లను భద్రపరచండి',
    },
    calendar: {
      title: 'హిందూ క్యాలెండర్',
      todayTithi: 'నేటి తిథి',
      upcomingFestivals: 'రాబోయే పండుగలు',
      shuklaPakshaChaturthi: 'శుక్ల పక్ష చతుర్థి',
      recommendedPoojas: 'సిఫార్సు చేయబడిన పూజలు',
      offerSeva: 'సేవ సమర్పించండి',
      legendFestival: 'పండుగ',
      legendEkadashi: 'ఏకాదశి',
      legendAmavasya: 'అమావాస్య',
      legendPournami: 'పౌర్ణమి',
      eventUgadiTitle: '14 ఏప్రిల్ — ఉగాది (తెలుగు నూతన సంవత్సరం)',
      eventUgadiDesc: 'తెలుగు మరియు కన్నడ నూతన సంవత్సరం. నూతన ప్రారంభాలకు, ఆస్తుల కొనుగోలుకు మరియు ప్రత్యేక ప్రార్థనలను సమర్పించడానికి అత్యంత శుభ దినం.',
      eventRamNavamiTitle: '17 ఏప్రిల్ — శ్రీరామ నవమి',
      eventRamNavamiDesc: 'శ్రీరాముని జన్మదినం. మానసిక శాంతికి, చిత్తశుద్ధికి మరియు పవిత్ర నామ స్మరణకు అనుకూలమైనది.',
      eventAmavasyaTitle: '18 ఏప్రిల్ — అమావాస్య',
      eventAmavasyaDesc: 'అమావాస్య. పితృ దేవతల ఆశీస్సులకు, ప్రతికూల కర్మల నుండి విముక్తికి మరియు శుద్ధి హోమాలను నిర్వహించడానికి అత్యంత శక్తివంతమైన సమయం.',
      eventPournamiTitle: '3 ఏప్రిల్ — పౌర్ణమి',
      eventPournamiDesc: 'పౌర్ణమి. దివ్య శక్తిని పొందడానికి, ధ్యానానికి మరియు కుటుంబ శ్రేయస్సు కొరకు సత్యనారాయణ వ్రతానికి అత్యంత అనుకూలమైనది.',
      eventEkadashiTitle: '{day} ఏప్రిల్ — ఏకాదశి',
      eventEkadashiDesc: 'విష్ణుమూర్తికి అంకితం చేయబడిన పవిత్ర దినం. ఉపవాసానికి, మానసిక స్పష్టతకు మరియు आध्यात्मिक ప్రగతికి ఎంతో ప్రయోజనకరం.',
      dayTitle: '{day} ఏప్రిల్',
      dayDesc: 'నిత్య ప్రార్థనలు, ధ్యానం మరియు ఆలయాలలో పవిత్ర అర్చనలను సమర్పించడానికి అనుకూలమైన రోజు.',
      april: 'ఏప్రిల్',
      weekday0: 'ఆ',
      weekday1: 'సో',
      weekday2: 'మ',
      weekday3: 'బు',
      weekday4: 'గు',
      weekday5: 'శు',
      weekday6: 'శ',
    },
    festival: {
      ugadi: 'ఉగాది',
      ugadiDesc: 'తెలుగు మరియు కన్నడ నూతన సంవత్సరం',
      ramNavami: 'శ్రీరామ నవమి',
      ramNavamiDesc: 'శ్రీరాముని జన్మదినం',
      vishu: 'విషు',
      vishuDesc: 'మలయాళ నూతనసంవత్సరం',
      hanumanJayanti: 'హనుమజ్జయంతి',
      hanumanJayantiDesc: 'హనుమంతుని జన్మదినం',
    },
    help: {
      title: 'సహాయం & మద్దతు',
      contactSupport: 'మద్దతును సంప్రదించండి',
      faq: 'తరచుగా అడిగే ప్రశ్నలు',
      faq1Q: 'నేను పూజను ఎలా బుక్ చేయాలి?',
      faq1A: "పూజలను బ్రౌజ్ చేయండి, మీ ప్రాధాన్య ఆలయం మరియు సమయాన్ని ఎంచుకోండి, ఆపై మీ బుకింగ్‌ను పూర్తి చేయడానికి 'ఈ పూజను సమర్పించండి' పై క్లిక్ చేయండి.",
      faq2Q: 'నేను పూజను లైవ్‌లో చూడవచ్చా?',
      faq2A: "అవును! మీ పూజ ప్రారంభమైనప్పుడు, మీకు నోటిఫికేషన్ వస్తుంది. నిజ సమయంలో వీక్షించడానికి మీ బుకింగ్‌లలో 'లైవ్ చూడండి' పై క్లిక్ చేయండి.",
      faq3Q: 'ప్రసాదం ఎలా డెలివరీ చేయబడుతుంది?',
      faq3A: 'మీ పూజ పూర్తయిన తర్వాత, ప్రసాదం జాగ్రత్తగా ప్యాక్ చేయబడి మీ చిరునామాకు పంపబడుతుంది.',
    },
    language: {
      label: 'భాష',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
    deity: {
      ganesha: 'గణపతి',
      lakshmi: 'లక్ష్మి',
      shiva: 'శివుడు',
      vishnu: 'విష్ణువు',
      durga: 'దుర్గ',
      saraswati: 'సరస్వతి',
      hanuman: 'హనుమంతుడు',
      murugan: 'మురుగన్',
    },
    poojaDb: {
      1: { title: 'రుద్రాభిషేకం', purpose: 'ఆధ్యాత్మిక శుద్ధి కొరకు శివునికి పవిత్రమైన స్నాన ఆచారం' },
      2: { title: 'విష్ణు అభిషేకం', purpose: 'ఐశ్వర్యం మరియు శాంతి కొరకు విష్ణుమూర్తికి దివ్యమైన స్నాన వేడుక' },
      3: { title: 'లక్ష్మీ అభిషేకం', purpose: 'ధనాన్ని ఆకర్షించడానికి లక్ష్మీ దేవికి పవిత్రమైన స్నాన ఆచారం' },
      4: { title: 'గణేశ అభిషేకం', purpose: 'విఘ్నాలను తొలగించి నూతన ప్రారంభాలకు ఆశీస్సులు పొందండి' },
      5: { title: 'సరస్వతి అభిషేకం', purpose: 'జ్ఞానం, వివేకం మరియు కళాత్మక నైపుణ్యాలను పెంపొందించుకోండి' },
      6: { title: 'గణపతి హోమం', purpose: 'విఘ్నాలను తొలగించి కార్యాలలో విజయం సాధించడానికి హోమం' },
      7: { title: 'నవగ్రహ హోమం', purpose: 'గ్రహాల ప్రభావాలను సమతుల్యం చేసి దోషాలను తొలగిస్తుంది' },
      8: { title: 'లక్ష్మీ కుబేర హోమం', purpose: 'సంపద, ఐశ్వర్యం మరియు ఆర్థిక సమృద్ధిని ఆకర్షిస్తుంది' },
      9: { title: 'సుదర్శన హోమం', purpose: 'ప్రతికూల శక్తులు మరియు చెడు శక్తుల నుండి రక్షణ' },
      10: { title: 'మహా మృత్యుంజయ హోమం', purpose: 'ఆరోగ్యం, దీర్ఘాయువు మరియు మృత్యువుపై విజయాన్ని చేకూరుస్తుంది' },
      11: { title: 'సహస్రనామ అర్చన', purpose: 'దివ్యమైన ఆశీస్సుల కొరకు విష్ణుమూర్తి యొక్క 1000 నామాలను జపించడం' },
      12: { title: 'లలితా సహస్రనామ అర్చన', purpose: 'దివ్యమైన స్త్రీ शक्ति మరియు ఆశీస్సులను ఆహ్వానించండి' },
      13: { title: 'అష్టోత్తర శతనామావళి', purpose: 'త్వరిత ఆశీస్సులు మరియు విఘ్నాల నివారణ కొరకు 108 నామాలను సమర్పించడం' },
      14: { title: 'హనుమాన్ చాలీసా అర్చన', purpose: 'కష్టాల నుండి శక్తి, ధైర్యం మరియు రక్షణను పొందండి' },
      15: { title: 'దుర్గా అష్టోత్తర అర్చన', purpose: 'రక్షణ మరియు శక్తి కొరకు జగన్మాత యొక్క ఆశీస్సులు' },
      16: { title: 'సత్యనారాయణ వ్రతం', purpose: 'కోరికలు నెరవేరడం మరియు ఐశ్వర్యం కొరకు సంపూర్ణ వ్రతం' },
      17: { title: 'వరలక్ష్మీ వ్రతం', purpose: 'కుటుంబ శ్రేయస్సు మరియు సమృద్ధి కొరకు ప్రత్యేక వ్రతం' },
      18: { title: 'కలశాభిషేకం', purpose: 'సంపూర్ణ శుద్ధి కొరకు కలశాలతో కూడిన భవ్యమైన అభిషేకం' },
      19: { title: 'ప్రదోషం ప్రత్యేక పూజ', purpose: 'పాప విముక్తి కొరకు ప్రదోష సమయంలో నిర్వహించబడుతుంది' },
      20: { title: 'ఏకాదశి ప్రత్యేక పూజ', purpose: 'ఆధ్యాత్మిక ఉన్నతి కొరకు ఏకాదశి నాడు శుభ పూజ' }
    },
    templeDb: {
      tirumala: { name: 'తిరుమల ఆలయం', location: 'ఆంధ్ర ప్రదేశ్', deity: 'వెంకటేశ్వర స్వామి', description: 'ప్రపంచంలోనే అత్యంత ధనిక మరియు అత్యధికంగా సందర్శించే పుణ్యక్షేత్రాలలో ఒకటి' },
      rameshwaram: { name: 'రామేశ్వరం ఆలయం', location: 'తమిళనాడు', deity: 'శివుడు', description: 'రామేశ్వరం ద్వీపంలో ఉన్న పవిత్ర జ్యోతిర్లింగ ఆలయం' },
      madurai: { name: 'మదురై ఆలయం', location: 'తమిళనాడు', deity: 'మీనాక్షి అమ్మవారు', description: 'మీనాక్షి రూపంలో పార్వతీ దేవికి అంకితం చేయబడిన చారిత్రాత్మక ఆలయం' },
      varanasi: { name: 'వారణాసి ఆలయం', location: 'ఉత్తర ప్రదేశ్', deity: 'శివుడు', description: 'పవిత్ర గంగా నది ఒడ్డున ఉన్న పురాతన ఆలయం' },
      siddhiVinayak: { name: 'సిద్ధి వినాయక ఆలయం', location: 'మహారాష్ట్ర', deity: 'గణపతి', description: 'ముంబైలో గణపతికి అంకితం చేయబడిన ప్రసిద్ధ ఆలయం' }
    }
  },
  hi: {
    common: {
      search: 'पूजा खोजें...',
      viewAll: 'सभी देखें',
      upcoming: 'आगामी',
      active: 'सक्रिय',
      completed: 'पूर्ण',
      cancel: 'रद्द करें',
      save: 'सहेजें',
      continue: 'जारी रखें',
      back: 'वापस',
      edit: 'संपादित करें',
      signOut: 'साइन आउट',
      close: 'बंद करें',
      viewDetails: 'विवरण देखें',
      bookNow: 'अभी बुक करें',
      free: 'मुफ़्त',
      included: 'शामिल',
      clearAll: 'सब कुछ साफ़ करें',
      signIn: 'Sign In',
      offerSeva: 'सेवा अर्पित करें',
      tomorrow: 'कल',
      optional: 'वैकल्पिक',
    },
    nav: {
      home: 'होम',
      poojas: 'पूजा',
      bookings: 'बुकिंग',
      temples: 'मंदिर',
      profile: 'प्रोफ़ाइल',
    },
    home: {
      greeting: 'नमस्ते',
      subtitle: 'आज एकादशी है — विष्णु पूजा के लिए शुभ दिन।',
      featuredTemples: 'विशेष मंदिर',
      categories: 'पूजा श्रेणियाँ',
      upcomingPoojas: 'आगामी पूजा',
      notifications: 'सूचनाएं',
      noNotifications: 'कोई नई सूचना नहीं',
      viewNotification: 'देखें',
      recommendedForYou: 'आपके लिए अनुशंसित',
      basedOnNakshatra: 'आपके नक्षत्र के आधार पर',
      nextLivePooja: 'अगली लाइव पूजा',
      nextLivePoojaName: 'श्री कालहस्ती में रुद्राभिषेक',
      offerSevaAmount: 'सेवा अर्पित करें — १,१००',
      upcoming: 'आगामी',
      temples: 'मंदिर',
      forYou: 'आपके लिए',
      live: 'लाइव',
      poojasCount: '{count} पूजा',
      today: 'आज',
      ekadashi: 'एकादशी',
      purnima: 'पूर्णिमा',
      wed: 'बुध',
      thu: 'गुरु',
      fri: 'शुक्र',
      sat: 'शनि',
      sun: 'रवि',
      mon: 'सोम',
      tue: 'मंगल',
      lakshmiPooja: 'लक्ष्मी पूजा',
      maduraiTemple: 'मधुरै मंदिर',
      rameshwaramTemple: 'रामेश्वरम मंदिर',
      satyanarayanaPooja: 'सत्यनारायण पूजा',
      tirumalaTemple: 'तिरुमला मंदिर',
      tirumala: 'तिरुमला',
      lordVenkateswara: 'भगवान वेंकटेश्वर',
      tirupati: 'तिरुपति',
      rameshwaram: 'रामेश्वरम',
      lordShiva: 'भगवान शिव',
      tamilNadu: 'तमिलनाडु',
      madurai: 'मधुरै',
      goddessMeenakshi: 'देवी मीनाक्षी',
      notificationLiveTitle: 'लाइव पूजा जल्द ही शुरू हो रही है',
      notificationLiveMessage: 'श्री कालहस्ती में रुद्राभिषेक 2 घंटे में शुरू होगा',
      notificationLiveTime: '2 घंटे पहले',
      notificationConfirmationTitle: 'पूजा की पुष्टि हो गई है',
      notificationConfirmationMessage: 'आपकी लक्ष्मी पूजा कल के लिए निर्धारित की गई है',
      notificationConfirmationTime: '1 दिन पहले',
      notificationFestivalTitle: 'आगामी त्योहार',
      notificationFestivalMessage: 'कल एकादशी है - विष्णु पूजा बुक करें',
      notificationFestivalTime: '2 दिन पहले',
    },
    categories: {
      abhishekam: 'अभिषेक',
      homam: 'होमम',
      archana: 'अर्चना',
      specialPoojas: 'विशेष पूजा',
      all: 'सभी पूजा',
    },
    poojas: {
      title: 'पवित्र पूजा',
      subtitle: 'प्रामाणिक मंदिर अनुष्ठान खोजें',
      searchPlaceholder: 'पूजा खोजें...',
      filters: 'फ़िल्टर',
      noPoojas: 'कोई पूजा नहीं मिली',
      liveStream: 'लाइव स्ट्रीम उपलब्ध',
      prasadIncluded: 'प्रसाद शामिल',
      duration: 'अवधि',
      min: 'मिनट',
    },
    poojaDetail: {
      overview: 'अवलोकन',
      where: 'कहाँ',
      how: 'कैसे',
      why: 'क्यों',
      offerPooja: 'यह पूजा अर्पित करें',
      sevaAmount: 'सेवा राशि',
      duration: 'अवधि',
      liveStreamAvailable: 'लाइव स्ट्रीम उपलब्ध',
      prasadIncluded: 'प्रसाद शामिल',
      whereTitle: 'यह पूजा कहाँ आयोजित की जाती है',
      howTitle: 'यह पूजा कैसे आयोजित की जाती है',
      whyTitle: 'भक्त इस पूजा को क्यों अर्पित करते हैं',
      suitableForRashi: 'राशि के लिए उपयुक्त',
      blessings: 'आशीर्वाद',
      healthLongevity: 'स्वास्थ्य और दीर्घायु',
      removalObstacles: 'बाधाओं का निवारण',
      peaceMind: 'मानसिक शांति',
      sanskrit: 'संस्कृत',
      telugu: 'तेलुगु',
      pujariName: 'पंडित रमेश शर्मा',
      pujariInfo: '22 वर्षों का अनुभव • तेलुगु, संस्कृत',
      step1Name: 'गणपति वंदनम',
      step1Desc: 'बाधाओं को दूर करने के लिए भगवान गणेश का आह्वान।',
      step2Name: 'पुण्याहवाचनम',
      step2Desc: 'स्थान और भक्त का शुद्धिकरण।',
      step3Name: 'शिवलिंग अभिषेक',
      step3Desc: 'जल, दूध, दही, शहद और घी से पवित्र स्नान।',
      step4Name: 'बिल्वार्चना',
      step4Desc: 'शिव के प्रत्येक नाम का जाप करते हुए 108 बिल्व पत्र अर्पित करना।',
      step5Name: 'मंगल आरती',
      step5Desc: 'कर्पूर और शंख ध्वनि के साथ आरती का समापन।',
      homamStep1Name: 'गणपति पूजा',
      homamStep1Desc: 'यज्ञ निर्विघ्न संपन्न हो, इसके लिए भगवान गणेश की पूजा।',
      homamStep2Name: 'संकल्प',
      homamStep2Desc: 'भक्तों के नाम, नक्षत्र और गोत्र के साथ यज्ञ के उद्देश्यों की घोषणा।',
      homamStep3Name: 'अग्नि प्रतिष्ठा',
      homamStep3Desc: 'पवित्र वेदी पर यज्ञ कुंड की स्थापना और अग्नि देव का आह्वान।',
      homamStep4Name: 'होम आहुति',
      homamStep4Desc: 'मंत्रोच्चार के साथ घी, जड़ी-बूटियों और समिधा की आहुति।',
      homamStep5Name: 'पूर्णाहुति एवं आरती',
      homamStep5Desc: 'यज्ञ की पूर्णाहुति के साथ अंतिम आहुति और आरती।',
      archanaStep1Name: 'संकल्प',
      archanaStep1Desc: 'विशेष प्रार्थना के लिए भक्त के नाम, नक्षत्र और गोत्र का उच्चारण।',
      archanaStep2Name: 'अष्टोत्तर शतनामावली',
      archanaStep2Desc: 'पुष्प या अक्षत अर्पित करते हुए देवता के 108 नामों का पाठ।',
      archanaStep3Name: 'पुष्पार्चन',
      archanaStep3Desc: 'ताजे फूलों से देवता का अर्चन करना।',
      archanaStep4Name: 'नैवेद्य',
      archanaStep4Desc: 'देवता को नारियल, फल and मिष्ठान का भोग लगाना।',
      archanaStep5Name: 'मंगल आरती',
      archanaStep5Desc: 'कपूर की ज्योति से आरती करना और आशीर्वाद प्राप्त करना।',
      specialStep1Name: 'कलश पूजा',
      specialStep1Desc: 'पवित्र कलश में वरुण देव और पवित्र नदियों का आह्वान।',
      specialStep2Name: 'प्रधान पूजा',
      specialStep2Desc: 'मुख्य देवता की षोडशोपचार पूजा, श्रृंगार और विशेष भोग।',
      specialStep3Name: 'व्रत कथा',
      specialStep3Desc: 'व्रत की पौराणिक कथा का श्रवण और पठन।',
      specialStep4Name: 'नैवेद्य एवं प्रसाद',
      specialStep4Desc: 'भोग लगाना और वितरित किए जाने वाले प्रसाद की तैयारी।',
      specialStep5Name: 'मंगल आरती',
      specialStep5Desc: 'पूजा की समाप्ति पर आरती और शांति पाठ।',
      wealthProsperity: 'धन और समृद्धि',
      protectionNegative: 'नकारात्मक ऊर्जा से सुरक्षा',
      devotionGrace: 'दैवीय कृपा और भक्ति',
      wishFulfillment: 'मनोकामना पूर्ति',
      familyWellbeing: 'पारिवारिक कल्याण',
      requirementsTitle: 'आवश्यक सामग्री',
      requirementsDesc: 'सभी पूजा सामग्री और प्रसाद की व्यवस्था मंदिर द्वारा की जाती है। भक्तों को कुछ भी प्रदान करने की आवश्यकता नहीं है।',
      notesTitle: 'महत्वपूर्ण निर्देश',
      notesDesc: 'पूजा आपके नाम और गोत्र के साथ की जाएगी। प्रसाद वितरण की जानकारी पूरा होने के 24 घंटे के भीतर बुकिंग टैब में अपडेट कर दी जाएगी।',
      faqTitle: 'पूजा प्रश्नोत्तरी',
      faqQ1: 'क्या मुझे ऑनलाइन उपस्थित रहना होगा?',
      faqA1: 'नहीं। पुजारी आपके नाम का संकल्प करेंगे। आप लाइव प्रसारण देख सकते हैं या बाद में रिकॉर्डिंग देख सकते हैं।',
    },
    welcome: {
      tagline: 'जहाँ तकनीक और भक्ति का मिलन होता है',
      subtitle: 'आप जहाँ भी हों, पूजा के लिए आपका पवित्र स्थान।',
      continueMobile: 'मोबाइल के साथ जारी रखें',
      termsAgree: 'जारी रखकर आप हमारी शर्तों और गोपनीयता नीति से सहमत होते हैं',
    },
    login: {
      brandSubtitle: 'पवित्र पूजा और अनुष्ठान प्रसाद',
      signInMobile: 'मोबाइल के साथ साइन इन',
      enterPhoneDesc: 'एक बार का पासवर्ड (OTP) प्राप्त करने के लिए अपना फ़ोन नंबर दर्ज करें।',
      enterPhonePlaceholder: 'मोबाइल नंबर दर्ज करें',
      errorPhone: 'कृपया एक वैध 10-अंकीय मोबाइल नंबर दर्ज करें',
      sendingOtp: 'ओटीपी भेज रहा है...',
      sendOtp: 'ओटीपी भेजें',
      verifyOtp: 'ओटीपी सत्यापित करें',
      otpSentDesc: "हमने +91 {number} पर 6-अंकीय ओटीपी भेजा है",
      enterOtpPlaceholder: '6-अंकीय ओटीपी दर्ज करें',
      errorOtp: 'कृपया 6-अंकीय ओटीपी दर्ज करें',
      resendOtp: 'ओटीपी पुनः भेजें',
      verifying: 'सत्यापित किया जा रहा है...',
      verifyLogin: 'सत्यापित करें और लॉगिन करें',
    },
    setup: {
      title: 'आप किन देवी-देवताओं को सबसे करीब मानते हैं?',
      subtitle: 'हम आपके उत्तर के आधार पर आपकी पूजा के सुझावों को व्यक्तिगत बनाएंगे।',
      skip: 'अभी के लिए छोड़ें',
    },
    live: {
      onBehalfOf: 'यह सेवा इनकी ओर से की जा रही है:',
      smooth: 'सुगम',
      devoteesJoined: '{count} भक्त शामिल हुए',
      guidance: '🙏 यदि आप मंत्र जानते हैं तो पुजारी के साथ जप करें। मंगल आरती के दौरान अपने घर के मंदिर में दीया जलाएं।',
    },
    booking: {
      date1: '18 अप्रैल 2026',
      date2: '22 अप्रैल 2026',
      date3: '15 अप्रैल 2026',
      stepInfo: 'चरण {step}/3',
      selectDateTime: 'तिथि और समय चुनें',
      yourDetails: 'आपका विवरण',
      reviewConfirm: 'समीक्षा और पुष्टि करें',
      selectDate: 'तिथि चुनें',
      selectTime: 'समय चुनें',
      devoteeNames: 'भक्त के नाम',
      devoteeNamesDesc: 'इन नामों में पूजा की जाएगी',
      devoteeNamesPlaceholder: 'नाम दर्ज करें',
      gothram: 'गोत्र',
      gothramPlaceholder: 'गोत्र दर्ज करें',
      nakshatra: 'नक्षत्र',
      nakshatraPlaceholder: 'नक्षत्र चुनें',
      specialRequests: 'विशेष अनुरोध',
      specialRequestsPlaceholder: 'कोई विशेष प्रार्थना या इरादे...',
      poojaDetails: 'पूजा विवरण',
      paymentSummary: 'भुगतान सारांश',
      poojaAmount: 'पूजा राशि',
      prasadDelivery: 'प्रसाद डिलीवरी',
      liveStream: 'लाइव स्ट्रीम',
      totalAmount: 'कुल राशि',
      proceedToPayment: 'भुगतान के लिए आगे बढ़ें',
      note: 'नोट',
      confirmationNote: 'भुगतान पूरा होने के बाद आपको बुकिंग विवरण और लाइव स्ट्रीम लिंक के साथ पुष्टि प्राप्त होगी।',
      completePayment: 'सेवा भुगतान पूरा करें',
      sevaDetails: 'सेवा विवरण',
      totalPrice: 'कुल सेवा मूल्य',
      paidAdvance: 'भुगतान की गई राशि (अग्रिम)',
      remainingBalanceDue: 'शेष बकाया राशि',
      payBalanceAmount: 'बकाया भुगतान करें — ₹{amount}',
      processingOffering: 'पवित्र प्रसाद को संसाधित किया जा रहा है...',
      processingDesc: 'कृपया ऐप बंद न करें या वापस न दबाएं। हम मंदिर के सुरक्षित गेटवे से जुड़ रहे हैं।',
      paymentSuccess: 'भुगतान सफल रहा! 🙏',
      confirmSuccess: "आपकी सेवा '{title}' अब पूरी तरह से पुष्ट हो गई है।",
      sankalpamNote: 'मंदिर के पुजारी आपके नाम से संकल्प मंत्र का जाप करेंगे। प्रसाद वितरण की ट्रैकिंग जानकारी जल्द ही अपडेट की जाएगी।',
    },
    bookingConfirmation: {
      title: 'आपकी सेवा अर्पित की गई है',
      subtitle: 'आपके नाम और गोत्र में पूजा की जाएगी। आप और आपके परिवार को आशीर्वाद मिले।',
      bookingConfirmed: 'बुकिंग पुष्टि की गई',
      bookingId: 'बुकिंग आईडी',
      viewJourney: 'पूर्ण यात्रा देखें',
      backToHome: 'होम पर वापस जाएं',
      setReminder: 'अनुस्मारक सेट करें',
      shareBlessing: 'आशीर्वाद साझा करें',
    },
    bookings: {
      title: 'मेरी बुकिंग',
      subtitle: 'अपनी पूजा यात्रा ट्रैक करें',
      active: 'सक्रिय',
      completed: 'पूर्ण',
      noActive: 'कोई सक्रिय बुकिंग नहीं',
      noCompleted: 'कोई पूर्ण बुकिंग नहीं',
      noActiveDesc: 'अपनी पहली पूजा बुक करें',
      noCompletedDesc: 'पूर्ण पूजाएं यहां दिखाई देंगी',
      viewJourney: 'पूर्ण यात्रा देखें',
      watchRecording: 'रिकॉर्डिंग देखें',
      trackPrasad: 'प्रसाद ट्रैक करें',
      poojaJourney: 'पूजा यात्रा',
    },
    journey: {
      title: 'पूजा यात्रा',
      sevaOffered: 'सेवा अर्पित',
      pujariAssigned: 'पुजारी नियुक्त',
      confirmed: 'पुष्टि की गई',
      poojaScheduled: 'निर्धारित',
      goingLive: 'पूजा लाइव',
      poojaCompleted: 'पूर्ण',
      recordingReady: 'रिकॉर्डिंग तैयार',
      prasadPacked: 'प्रसाद पैक किया गया',
      prasadDispatched: 'भेजा गया',
      prasadDelivered: 'वितरित',
      sankalpamDetails: 'संकल्प विवरण',
      poojaSeva: 'पूजा सेवा',
      templeLocation: 'मंदिर का स्थान',
      devoteeName: 'भक्त का नाम',
      gothramNakshatra: 'गोत्र / नक्षत्र',
      watchBroadcast: 'वीडियो प्रसारण देखें',
      trackPrasad: 'प्रसाद बॉक्स ट्रैक करें',
      sevaOfferedDesc: 'आपका अनुष्ठान अनुरोध भक्ति के साथ प्राप्त हुआ है।',
      pujariAssignedDesc: 'आपकी सेवा के लिए पण्डित रमेश शर्मा को नियुक्त किया गया है।',
      poojaScheduledDesc: 'संकल्प १५ अप्रैल को सुबह ९:०० बजे निर्धारित है।',
      goingLiveDesc: 'पवित्र सीधा प्रसारण किया गया। आशीर्वाद साझा किया गया।',
      poojaCompletedDesc: 'आपके नाम और गोत्र में पूजा सफलतापूर्वक संपन्न हुई।',
      recordingReadyDesc: 'आपका समर्पित पूजा वीडियो संग्रह तैयार किया जा रहा है।',
      prasadPackedDesc: 'देवसेवा आशीर्वाद बॉक्स में पवित्र सामग्रियां पैक की गई हैं।',
      prasadDispatchedDesc: 'आपका प्रसाद रास्ते में है। ट्रैकिंग विवरण लंबित है।',
      prasadDeliveredDesc: 'पवित्र प्रसाद आपके घर में शांति लाए।',
    },
    temples: {
      title: 'पवित्र मंदिर',
      subtitle: 'दिव्य मंदिरों का अन्वेषण करें',
      explore: 'अन्वेषण करें',
      hide: 'छुपाएं',
      availablePoojas: 'उपलब्ध पूजा',
      location: 'स्थान',
    },
    profile: {
      title: 'प्रोफ़ाइल',
      personalisation: 'वैयक्तिकरण',
      aiRecommendations: 'आपकी पवित्र सिफारिशें',
      settings: 'सेटिंग्स',
      theme: 'थीम',
      darkMode: 'डार्क मोड',
      lightMode: 'लाइट मोड',
      notifications: 'सूचनाएं',
      hinduCalendar: 'हिंदू कैलेंडर',
      helpSupport: 'सहायता और समर्थन',
      appSettings: 'ऐप सेटिंग्स',
      signOut: 'साइन आउट',
      version: 'भक्ति के साथ बनाया गया',
      editProfile: 'प्रोफ़ाइल संपादित करें',
      editPersonalInfo: 'व्यक्तिगत जानकारी संपादित करें',
      fullName: 'पूरा नाम',
      email: 'ईमेल',
      phone: 'फ़ोन',
      location: 'स्थान',
      nakshatra: 'नक्षत्र',
      rashi: 'राशि',
      dateOfBirth: 'जन्म तिथि',
      gothram: 'गोत्र',
      saveChanges: 'परिवर्तन सहेजें',
      recommendationsTitle: 'आपके नक्षत्र के आधार पर',
      recommendationsDesc: 'आपके लिए व्यक्तिगत पूजा सिफारिशें',
      viewRecommendations: 'सिफारिशें देखें',
      totalPoojas: 'पूजा',
      upcomingCount: 'आगामी',
      devotionScore: 'भक्ति',
      ishtaDevatas: 'इष्ट देवता (देवी-देवता प्राथमिकताएं)',
      noDeities: 'अभी तक कोई देवता नहीं चुना गया',
      selectIshtaDevatas: 'इष्ट देवता चुनें',
      savePreferences: 'प्राथमिकताएं सहेजें',
      val: {
        priya: 'प्रिया',
        raghavan: 'राघवन अय्यर',
        bangalore: 'बेंगलुरु, कर्नाटक',
        shravana: 'श्रवण',
        makara: 'मकर राशि (मकर)',
        dob: '15 जनवरी 1990',
        bharadwaja: 'भारद्वाज'
      }
    },
    notifications: {
      title: 'सूचना सेटिंग्स',
      poojaReminders: 'पूजा अनुस्मारक',
      poojaRemindersDesc: 'अपनी निर्धारित पूजा से पहले याद दिलाएं',
      liveStreams: 'लाइव स्ट्रीम',
      liveStreamsDesc: 'जब आपकी पूजा स्ट्रीमिंग शुरू हो तो सूचना',
      prasadUpdates: 'प्रसाद अपडेट',
      prasadUpdatesDesc: 'अपने प्रसाद डिलीवरी स्थिति को ट्रैक करें',
      festivalAlerts: 'त्योहार अलर्ट',
      festivalAlertsDesc: 'विशेष पूजा और त्योहार सूचनाएं',
      saveSettings: 'सेटिंग्स सहेजें',
    },
    calendar: {
      title: 'हिंदू कैलेंडर',
      todayTithi: 'आज की तिथि',
      upcomingFestivals: 'आगामी त्योहार',
      shuklaPakshaChaturthi: 'शुक्ल पक्ष चतुर्थी',
      recommendedPoojas: 'अनुशंसित पूजा',
      offerSeva: 'सेवा अर्पित करें',
      legendFestival: 'त्योहार',
      legendEkadashi: 'एकादशी',
      legendAmavasya: 'अमावस्या',
      legendPournami: 'पूर्णिमा',
      eventUgadiTitle: '14 अप्रैल — उगादि (तेलुगु नव वर्ष)',
      eventUgadiDesc: 'तेलुगु और कन्नड़ नव वर्ष। नई शुरुआत, संपत्ति खरीदने और विशेष प्रार्थना करने के लिए एक अत्यंत शुभ दिन।',
      eventRamNavamiTitle: '17 अप्रैल — श्री राम नवमी',
      eventRamNavamiDesc: 'भगवान राम की जयंती। शांति, मन की शुद्धि और पवित्र नामों के जप के लिए आदर्श।',
      eventAmavasyaTitle: '18 अप्रैल — अमावस्या',
      eventAmavasyaDesc: 'अमावस्या। पैतृक आशीर्वाद के लिए, नकारात्मक कर्मों को दूर करने और शुद्धि हवन करने के लिए एक अत्यंत शक्तिशाली समय।',
      eventPournamiTitle: '3 अप्रैल — पूर्णिमा',
      eventPournamiDesc: 'पूर्णिमा। दिव्य ऊर्जा प्राप्त करने, ध्यान और पारिवारिक समृद्धि के लिए सत्यनारायण व्रत करने के लिए शुभ।',
      eventEkadashiTitle: '{day} अप्रैल — एकादशी',
      eventEkadashiDesc: 'भगवान विष्णु को समर्पित एक पवित्र दिन। उपवास, मानसिक स्पष्टता और आध्यात्मिक प्रगति के लिए अत्यधिक फायदेमंद।',
      dayTitle: '{day} अप्रैल',
      dayDesc: 'दैनिक प्रार्थना, ध्यान और मंदिरों में पवित्र अर्चना करने के लिए एक शुभ दिन.',
      april: 'अप्रैल',
      weekday0: 'र',
      weekday1: 'सो',
      weekday2: 'मं',
      weekday3: 'बु',
      weekday4: 'गु',
      weekday5: 'शु',
      weekday6: 'श',
    },
    festival: {
      ugadi: 'उगादि',
      ugadiDesc: 'तेलुगु और कन्नड़ नव वर्ष',
      ramNavami: 'श्री राम नवमी',
      ramNavamiDesc: 'भगवान राम का जन्म',
      vishu: 'विषु',
      vishuDesc: 'मलयालम नव वर्ष',
      hanumanJayanti: 'हनुमान जयंती',
      hanumanJayantiDesc: 'भगवान हनुमान का जन्म',
    },
    help: {
      title: 'सहायता और समर्थन',
      contactSupport: 'समर्थन से संपर्क करें',
      faq: 'अक्सर पूछे जाने वाले प्रश्न',
      faq1Q: 'मैं पूजा कैसे बुक करूं?',
      faq1A: "पूजा ब्राउज़ करें, अपना पसंदीदा मंदिर और समय चुनें, फिर अपनी बुकिंग पूरी करने के लिए 'यह पूजा अर्पित करें' पर क्लिक करें।",
      faq2Q: 'क्या मैं पूजा लाइव देख सकता हूँ?',
      faq2A: "हाँ! जब आपकी पूजा शुरू होगी, तो आपको एक सूचना मिलेगी। वास्तविक समय में देखने के लिए अपनी बुकिंग में 'लाइव देखें' पर क्लिक करें।",
      faq3Q: 'प्रसाद कैसे वितरित किया जाता है?',
      faq3A: 'आपकी पूजा पूरी होने के बाद, प्रसाद को ध्यानपूर्वक पैक करके आपके पते पर भेज दिया जाता है।',
    },
    language: {
      label: 'भाषा',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
    deity: {
      ganesha: 'गणेश',
      lakshmi: 'लक्ष्मी',
      shiva: 'शिव',
      vishnu: 'विष्णु',
      durga: 'दुर्गा',
      saraswati: 'सरस्वती',
      hanuman: 'हनुमान',
      murugan: 'मुरुगन',
    },
    poojaDb: {
      1: { title: 'रुद्राभिषेक', purpose: 'आध्यात्मिक शुद्धि के लिए भगवान शिव के लिए पवित्र स्नान अनुष्ठान' },
      2: { title: 'विष्णु अभिषेक', purpose: 'समृद्धि और शांति के लिए भगवान विष्णु के लिए दिव्य स्नान समारोह' },
      3: { title: 'लक्ष्मी अभिषेक', purpose: 'धन को आकर्षित करने के लिए देवी लक्ष्मी के लिए पवित्र स्नान अनुष्ठान' },
      4: { title: 'गणेश अभिषेक', purpose: 'बाधाओं को दूर करें और नई शुरुआत के लिए आशीर्वाद लें' },
      5: { title: 'सरस्वती अभिषेक', purpose: 'ज्ञान, बुद्धि और कलात्मक क्षमताओं को बढ़ाएं' },
      6: { title: 'गणपति होमम', purpose: 'बाधाओं को दूर करने और प्रयासों में सफलता सुनिश्चित करने के लिए अग्नि अनुष्ठान' },
      7: { title: 'नवग्रह होमम', purpose: 'ग्रहों के प्रभावों को संतुलित करता है और दोषों को दूर करता है' },
      8: { title: 'लक्ष्मी कुबेर होमम', purpose: 'धन, समृद्धि और वित्तीय प्रचुरता को आकर्षित करता है' },
      9: { title: 'सुदर्शन होमम', purpose: 'नकारात्मक ऊर्जाओं और बुरी शक्तियों से सुरक्षा' },
      10: { title: 'महा मृत्युंजय होमम', purpose: 'स्वास्थ्य, दीर्घायु और मृत्यु पर विजय को बढ़ावा देता है' },
      11: { title: 'सहस्रनाम अर्चना', purpose: 'दिव्य आशीर्वाद के लिए भगवान विष्णु के 1000 नामों का जप' },
      12: { title: 'ललिता सहस्रनाम अर्चना', purpose: 'दिव्य स्त्री ऊर्जा और आशीर्वाद का आह्वान करें' },
      13: { title: 'अष्टोत्तर शतनामावली', purpose: 'शीघ्र आशीर्वाद और बाधा निवारण के लिए 108 नामों का अर्पण' },
      14: { title: 'हनुमान चालीसा अर्चना', purpose: 'कठिनाइयों से शक्ति, साहस और सुरक्षा प्राप्त करें' },
      15: { title: 'दुर्गा अष्टोत्तर अर्चना', purpose: 'सुरक्षा और शक्ति के लिए दिव्य माता का आशीर्वाद' },
      16: { title: 'सत्यनारायण व्रत', purpose: 'इच्छाओं की पूर्ति और समृद्धि के लिए पूर्ण व्रत' },
      17: { title: 'वरलक्ष्मी व्रत', purpose: 'पारिवारिक भलाई और प्रचुरता के लिए विशेष व्रत' },
      18: { title: 'कलशाभिषेक', purpose: 'पूर्ण शुद्धि के लिए पवित्र कलशों के साथ भव्य अभिषेक' },
      19: { title: 'प्रदोषम विशेष पूजा', purpose: 'पापों से मुक्ति के लिए प्रदोष काल में किया जाता है' },
      20: { title: 'एकादशी विशेष पूजा', purpose: 'आध्यात्मिक उन्नति के लिए एकादशी पर शुभ पूजा' }
    },
    templeDb: {
      tirumala: { name: 'तिरुमला मंदिर', location: 'आंध्र प्रदेश', deity: 'भगवान वेंकटेश्वर', description: 'दुनिया के सबसे अमीर और सबसे अधिक देखे जाने वाले तीर्थ केंद्रों में से एक' },
      rameshwaram: { name: 'रामेश्वरम मंदिर', location: 'तमिलनाडु', deity: 'भगवान शिव', description: 'रामेश्वरम द्वीप पर पवित्र ज्योतिर्लिंग मंदिर' },
      madurai: { name: 'मधुरै मंदिर', location: 'तमिलनाडु', deity: 'देवी मीनाक्षी', description: 'मीनाक्षी के रूप में देवी पार्वती को समर्पित ऐतिहासिक मंदिर' },
      varanasi: { name: 'वाराणसी मंदिर', location: 'उत्तर प्रदेश', deity: 'भगवान शिव', description: 'पवित्र गंगा नदी के तट पर प्राचीन मंदिर' },
      siddhiVinayak: { name: 'सिद्धि विनायक मंदिर', location: 'महाराष्ट्र', deity: 'भगवान गणेश', description: 'मुंबई में भगवान गणेश को समर्पित प्रसिद्ध मंदिर' }
    }
  },
  gu: {
    common: {
      search: 'પૂજા શોધો...',
      viewAll: 'બધું જુઓ',
      upcoming: 'આગામી',
      active: 'સક્રિય',
      completed: 'પૂર્ણ',
      cancel: 'રદ કરો',
      save: 'સાચવો',
      continue: 'ચાલુ રાખો',
      back: 'પાછળ',
      edit: 'સંપાદિત કરો',
      signOut: 'સાઇન આઉટ',
      close: 'બંધ કરો',
      viewDetails: 'વિગતો જુઓ',
      bookNow: 'હમણાં બુક કરો',
      free: 'મફત',
      included: 'સામેલ',
      clearAll: 'અન્ની સાફ કરો',
      signIn: 'સાઇન ઇન',
      offerSeva: 'સેવા અર્પણ કરો',
      tomorrow: 'આવતીકાલે',
      optional: 'વૈકલ્પિક',
    },
    nav: {
      home: 'હોમ',
      poojas: 'પૂજા',
      bookings: 'બુકિંગ',
      temples: 'મંદિરો',
      profile: 'પ્રોફાઇલ',
    },
    home: {
      greeting: 'નમસ્તે',
      subtitle: 'આજે એકાદશી છે — વિષ્ણુ પૂજા માટે શુભ દિવસ.',
      featuredTemples: 'વિશેષ મંદિરો',
      categories: 'પૂજા શ્રેણીઓ',
      upcomingPoojas: 'આગામી પૂજા',
      notifications: 'સૂચનાઓ',
      noNotifications: 'કોઈ નવી સૂચના નથી',
      viewNotification: 'જુઓ',
      recommendedForYou: 'તમારા માટે ભલામણ કરેલ',
      basedOnNakshatra: 'તમારા નક્ષત્ર પર આધારિત',
      nextLivePooja: 'આગામી લાઇવ પૂજા',
      nextLivePoojaName: 'શ્રી કાલહસ્તીમાં રુદ્રાભિષેક',
      offerSevaAmount: 'સેવા અર્પણ કરો — ₹૧,૧૦૦',
      upcoming: 'આગામી',
      temples: 'મંદિરો',
      forYou: 'તમારા માટે',
      live: 'લાઇવ',
      poojasCount: '{count} પૂજા',
      today: 'આજે',
      ekadashi: 'એકાદશી',
      purnima: 'પૂર્ણિમા',
      wed: 'બુધ',
      thu: 'ગુરૂ',
      fri: 'શુક્ર',
      sat: 'શનિ',
      sun: 'રવિ',
      mon: 'સોમ',
      tue: 'મંગળ',
      lakshmiPooja: 'લક્ષ્મી પૂજા',
      maduraiTemple: 'મદુરાઇ મંદિર',
      rameshwaramTemple: 'રામેશ્વરમ મંદિર',
      satyanarayanaPooja: 'સત્યનારાયણ પૂજા',
      tirumalaTemple: 'તિરુમલા મંદિર',
      tirumala: 'તિરુમલા',
      lordVenkateswara: 'ભગવાન વેંકટેશ્વર',
      tirupati: 'તિરુપતિ',
      rameshwaram: 'રામેશ્વરમ',
      lordShiva: 'ભગવાન શિવ',
      tamilNadu: 'તમિલનાડુ',
      madurai: 'મદુરાઇ',
      goddessMeenakshi: 'દેવી મીનાક્ષી',
      notificationLiveTitle: 'Live પૂજા ટૂંક સમયમાં શરૂ થશે',
      notificationLiveMessage: 'શ્રી કાલહસ્તીમાં રુદ્રાભિષેક ૨ કલાકમાં શરૂ થશે',
      notificationLiveTime: '૨ કલાક પહેલા',
      notificationConfirmationTitle: 'પૂજા પુષ્ટિ થઈ ગઈ છે',
      notificationConfirmationMessage: 'તમારી લક્ષ્મી પૂજા આવતીકાલ માટે સુનિશ્ચિત કરવામાં આવી છે',
      notificationConfirmationTime: '૧ દિવસ પહેલા',
      notificationFestivalTitle: 'આગામી તહેવાર',
      notificationFestivalMessage: 'આવતીકાલે એકાદશી છે - વિષ્ણુ પૂજા બુક કરો',
      notificationFestivalTime: '૨ દિવસ પહેલા',
    },
    categories: {
      abhishekam: 'અભિષેક',
      homam: 'હોમમ',
      archana: 'અર્ચના',
      specialPoojas: 'વિશેષ પૂજા',
      all: 'બધી પૂજા',
    },
    poojas: {
      title: 'પવિત્ર પૂજા',
      subtitle: 'પ્રામાણિક મંદિર વિધિઓ શોધો',
      searchPlaceholder: 'પૂજા શોધો...',
      filters: 'ફિલ્ટર્સ',
      noPoojas: 'કોઈ પૂજા મળી નથી',
      liveStream: 'લાઇવ સ્ટ્રીમ ઉપલબ્ધ',
      prasadIncluded: 'પ્રસાદ સામેલ',
      duration: 'અવધિ',
      min: 'મિનિટ',
    },
    poojaDetail: {
      overview: 'વિહંગાવલોકન',
      where: 'ક્યાં',
      how: 'કેવી રીતે',
      why: 'શા માટે',
      offerPooja: 'આ પૂજા અર્પણ કરો',
      sevaAmount: 'સેવા રકમ',
      duration: 'અવધિ',
      liveStreamAvailable: 'લાઇવ સ્ટ્રીમ ઉપલબ્ધ',
      prasadIncluded: 'પ્રસાદ સામેલ',
      whereTitle: 'આ પૂજા ક્યાં આયોજિત કરવામાં આવે છે',
      howTitle: 'આ પૂજા કેવી રીતે આયોજિત કરવામાં આવે છે',
      whyTitle: 'ભક્તો આ પૂજા શા માટે અર્પણ કરે છે',
      suitableForRashi: 'રાશિ માટે યોગ્ય',
      blessings: 'આશીર્વાદ',
      healthLongevity: 'આરોગ્ય અને દીર્ઘાયુષ્ય',
      removalObstacles: 'અવરોધો દૂર કરવા',
      peaceMind: 'માનસિક શાંતિ',
      sanskrit: 'સંસ્કૃત',
      telugu: 'તેલુગુ',
      pujariName: 'પંડિત રમેશ શર્મા',
      pujariInfo: '22 વર્ષનો અનુભવ • તેલુગુ, સંસ્કૃત',
      step1Name: 'ગણપતિ વંદનમ',
      step1Desc: 'અવરોધો દૂર કરવા માટે ભગવાન ગણેશની આરાધના.',
      step2Name: 'પુણ્યાહવાચનમ',
      step2Desc: 'સ્થળ અને ભક્તનું શુદ્ધિકરણ.',
      step3Name: 'શિવલિંગ અભિષેક',
      step3Desc: 'જળ, દૂધ, દહીં, મધ અને ઘીથી પવિત્ર સ્નાન.',
      step4Name: 'બિલ્વાર્ચના',
      step4Desc: 'શિવના પ્રત્યેક નામનો જાપ કરીને 108 બિલ્વપત્ર અર્પણ કરવા.',
      step5Name: 'મંગળ આરતી',
      step5Desc: 'કપૂર અને શંખનાદ સાથે આરતીની પૂર્ણાહુતિ.',
      homamStep1Name: 'ગણપતિ પૂજા',
      homamStep1Desc: 'યજ્ઞ નિર્વિઘ્ન પૂર્ણ થાય તે માટે ભગવાન ગણેશની આરાધના.',
      homamStep2Name: 'સંકલ્પ',
      homamStep2Desc: 'ભક્તોના નામ, નક્ષત્ર અને ગોત્ર સાથે યજ્ઞના હેતુઓનો સંકલ્પ.',
      homamStep3Name: 'અગ્નિ પ્રતિષ્ઠા',
      homamStep3Desc: 'પવિત્ર યજ્ઞકુંડની સ્થાપના અને અગ્નિ દેવનું આહ્વાન.',
      homamStep4Name: 'હોમ આહુતિ',
      homamStep4Desc: 'મંત્રોચ્ચાર સાથે ઘી, જડીબુટ્ટીઓ અને સમિધાઓની આહુતિ.',
      homamStep5Name: 'પૂર્ણાહુતિ અને આરતી',
      homamStep5Desc: 'યજ્ઞની સમાપ્તિ પર પૂર્ણ આહુતિ અને મંગળ આરતી.',
      archanaStep1Name: 'સંકલ્પ',
      archanaStep1Desc: 'વિશેષ પ્રાર્થના માટે ભક્તના નામ, નક્ષત્ર અને ગોત્રનો પાઠ.',
      archanaStep2Name: 'અષ્ટોત્તર શતનામાવલી',
      archanaStep2Desc: 'પુષ્પ અથવા અક્ષત અર્પણ કરીને દેવતાના 108 નામોનો પાઠ.',
      archanaStep3Name: 'પુષ્પાર્ચન',
      archanaStep3Desc: 'તાજા ફૂલોથી ભગવાનની અર્ચના કરવી.',
      archanaStep4Name: 'નૈવેદ્ય',
      archanaStep4Desc: 'ભગવાનને નાળિયેર, ફળ અને મીઠાઈનો ભોગ ધરાવવો.',
      archanaStep5Name: 'મંગળ આરતી',
      archanaStep5Desc: 'કપૂર પ્રગટાવીને ભગવાનની આરતી કરવી અને આશીર્વાદ મેળવવા.',
      specialStep1Name: 'કલશ પૂજા',
      specialStep1Desc: 'પવિત્ર કલશમાં વરુણ દેવ અને પવિત્ર નદીઓનું આહ્વાન.',
      specialStep2Name: 'પ્રધાન પૂજા',
      specialStep2Desc: 'મુખ્ય ભગવાનનીષોડશોપચાર પૂજા, શૃંગાર અને વિશેષ ભોગ.',
      specialStep3Name: 'વ્રત કથા',
      specialStep3Desc: 'વ્રતની પૌરાણિક કથાનું શ્રવણ અને પઠન.',
      specialStep4Name: 'નૈવેદ્ય અને પ્રસાદ',
      specialStep4Desc: 'ભોગ ધરાવવો અને વિતરણ માટે પ્રસાદ તૈયાર કરવો.',
      specialStep5Name: 'મંગળ આરતી',
      specialStep5Desc: 'પૂજાની સમાપ્તિ પર આરતી અને શાંતિ પાઠ.',
      wealthProsperity: 'ધન અને સમૃદ્ધિ',
      protectionNegative: 'નકારાત્મક ઉર્જાથી રક્ષણ',
      devotionGrace: 'દૈવી કૃપા અને ભક્તિ',
      wishFulfillment: 'મનોકામના પૂર્તિ',
      familyWellbeing: 'પારિવારિક કલ્યાણ',
      requirementsTitle: 'જરૂરી સામગ્રી',
      requirementsDesc: 'પૂજાની તમામ સામગ્રી અને પ્રસાદની વ્યવસ્થા મંદિર દ્વારા કરવામાં આવે છે. ભક્તોએ કંઈપણ આપવાની જરૂર નથી.',
      notesTitle: 'મહત્વપૂર્ણ નોંધો',
      notesDesc: 'પૂજા તમારા નામ અને ગોત્ર સાથે કરવામાં આવશે. પ્રસાદ વિતરણની માહિતી પૂજા પૂર્ણ થયાના 24 કલાકમાં બુકિંગ ટેબમાં અપડેટ કરવામાં આવશે.',
      faqTitle: 'પૂજા પ્રશ્નોત્તરી',
      faqQ1: 'શું મારે ઓનલાઇન હાજર રહેવું જરૂરી છે?',
      faqA1: 'ના. પૂજારી તમારા નામનો સંકલ્પ કરશે. તમે લાઇવ પ્રસારણ જોઈ શકો છો અથવા પછીથી રેકોર્ડિંગ જોઈ શકો છો.',
    },
    welcome: {
      tagline: 'જ્યાં ટેકનોલોજી અને ભક્તિનો સંગમ થાય છે',
      subtitle: 'તમે ગમે ત્યાં હોવ, પૂજા માટે તમારું પવિત્ર સ્થાન.',
      continueMobile: 'મોબાઇલ સાથે ચાલુ રાખો',
      termsAgree: 'આગળ વધીને તમે અમારી શરતો અને ગોપ્યતા નીતિ સાથે સહમત થાઓ છો',
    },
    login: {
      brandSubtitle: 'પવિત્ર પૂજા અને વિધિ અર્પણ',
      signInMobile: 'મોબાઇલ સાથે સાઇન ઇન',
      enterPhoneDesc: 'વન-ટાઇમ પાસવર્ડ (OTP) મેળવવા માટે તમારો ફોન નંબર દાખલ કરો.',
      enterPhonePlaceholder: 'મોબાઇલ નંબર દાખલ કરો',
      errorPhone: 'કૃપા કરીને માન્ય ૧૦-આંકડાનો મોબાઇલ નંબર દાખલ કરો',
      sendingOtp: 'OTP મોકલી રહ્યું છે...',
      sendOtp: 'OTP મોકલો',
      verifyOtp: 'OTP ચકાસો',
      otpSentDesc: "અમે +91 {number} પર ૬-આંકડાનો OTP મોકલ્યો છે",
      enterOtpPlaceholder: '૬-આંકડાનો OTP દાખલ કરો',
      errorOtp: 'કૃપા કરીને ૬-આંકડાનો OTP દાખલ કરો',
      resendOtp: 'OTP ફરીથી મોકલો',
      verifying: 'ચકાસી રહ્યું છે...',
      verifyLogin: 'ચકાસો અને લોગિન કરો',
    },
    setup: {
      title: 'તમે કયા દેવતાઓની સૌથી નજીક છો?',
      subtitle: 'અમે તમારા જવાબના આધારે તમારી પૂજા ભલામણોને વ્યક્તિગત કરીશું.',
      skip: 'હમણાં માટે છોડી દો',
    },
    live: {
      onBehalfOf: 'આ સેવા આમના વતી કરવામાં આવી રહી છે:',
      smooth: 'સરળ',
      devoteesJoined: '{count} ભક્તો જોડાયા',
      guidance: '🙏 જો તમે મંત્રો જાણતા હોવ તો પૂજારી સાથે જાપ કરો. મંગળ આરતી દરમિયાન તમારા ઘરના મંદિરમાં દીવો પ્રગટાવવા માટે સંકોચ ન કરશો.',
    },
    booking: {
      date1: '18 એપ્રિલ 2026',
      date2: '22 એપ્રિલ 2026',
      date3: '15 એપ્રિલ 2026',
      stepInfo: 'પગલું {step}/3',
      selectDateTime: 'તારીખ અને સમય પસંદ કરો',
      yourDetails: 'તમારી વિગતો',
      reviewConfirm: 'સમીક્ષા અને પુષ્ટિ કરો',
      selectDate: 'તારીખ પસંદ કરો',
      selectTime: 'સમય પસંદ કરો',
      devoteeNames: 'ભક્તોના નામ',
      devoteeNamesDesc: 'આ નામોમાં પૂજા કરવામાં આવશે',
      devoteeNamesPlaceholder: 'નામ દાખલ કરો',
      gothram: 'ગોત્ર',
      gothramPlaceholder: 'ગોત્ર દાખલ કરો',
      nakshatra: 'નક્ષત્ર',
      nakshatraPlaceholder: 'નક્ષત્ર પસંદ કરો',
      specialRequests: 'વિશેષ વિનંતીઓ',
      specialRequestsPlaceholder: 'કોઈ ચોક્કસ પ્રાર્થના અથવા ઇરાદા...',
      poojaDetails: 'પૂજા વિગતો',
      paymentSummary: 'ચુકવણી સારાંશ',
      poojaAmount: 'પૂજા રકમ',
      prasadDelivery: 'પ્રસાદ ડિલિવરી',
      liveStream: 'લાઇવ સ્ટ્રીમ',
      totalAmount: 'કુલ રકમ',
      proceedToPayment: 'ચુકવણી માટે આગળ વધો',
      note: 'નોંધ',
      confirmationNote: 'ચુકવણી પૂર્ણ થયા પછી તમને બુકિંગ વિગતો અને લાઇવ સ્ટ્રીમ લિંક સાથે પુષ્ટિ પ્રાપ્ત થશે.',
      completePayment: 'સેવા ચુકવણી પૂર્ણ કરો',
      sevaDetails: 'સેવા વિગતો',
      totalPrice: 'કુલ સેવા કિંમત',
      paidAdvance: 'ચૂકવેલ રકમ (એડવાન્સ)',
      remainingBalanceDue: 'બાકી રહેલ બેલેન્સ રકમ',
      payBalanceAmount: 'બાકી ચૂકવો — ₹{amount}',
      processingOffering: 'પવિત્ર અર્પણ પર પ્રક્રિયા થઈ રહી છે...',
      processingDesc: 'કૃપા કરીને એપ્લિકેશન બંધ કરશો નહીં અથવા પાછા દબાવો નહીં. અમે મંદિરના સુરક્ષિત ગેટવે સાથે જોડાઈ રહ્યા છીએ.',
      paymentSuccess: 'ચુકવણી સફળ રહી! 🙏',
      confirmSuccess: "તમારી સેવા '{title}' હવે સંપૂર્ણપણે પુષ્ટિ થઈ ગઈ છે.",
      sankalpamNote: 'મંદિરના પૂજારી તમારા નામે સંકલ્પ કરશે. પ્રસાદ વિતરણ ટ્રેકિંગ વિગતો ટૂંક સમયમાં અપડેટ કરવામાં આવશે.',
    },
    bookingConfirmation: {
      title: 'તમારી સેવા અર્પણ કરવામાં આવી છે',
      subtitle: 'તમારા નામ & ગોત્રમાં પૂજા કરવામાં આવશે. તમને અને તમારા પરિવારને આશીર્વાદ મળો.',
      bookingConfirmed: 'બુકિંગ પુષ્ટિ થઈ',
      bookingId: 'બુકિંગ આઈડી',
      viewJourney: 'સંપૂર્ણ યાત્રા જુઓ',
      backToHome: 'હોમ પર પાછા જાઓ',
      setReminder: 'રીમાઇન્ડર સેટ કરો',
      shareBlessing: 'આશીર્વાદ શેર કરો',
    },
    bookings: {
      title: 'મારી બુકિંગ',
      subtitle: 'તમારી પૂજા યાત્રા ટ્રેક કરો',
      active: 'સક્રિય',
      completed: 'પૂર્ણ',
      noActive: 'કોઈ સક્રિય બુકિંગ નથી',
      noCompleted: 'કોઈ પૂર્ણ બુકિંગ નથી',
      noActiveDesc: 'તમારી પહેલી પૂજા બુક કરો',
      noCompletedDesc: 'પૂર્ણ પૂજાઓ અહીં દેખાશે',
      viewJourney: 'સંપૂર્ણ યાત્રા જુઓ',
      watchRecording: 'રેકોર્ડિંગ જુઓ',
      trackPrasad: 'પ્રસાદ ટ્રેક કરો',
      poojaJourney: 'પૂજા યાત્રા',
    },
    journey: {
      title: 'પૂજા યાત્રા',
      sevaOffered: 'સેવા અર્પણ',
      pujariAssigned: 'પુજારી સોંપાયેલ',
      confirmed: 'પુષ્ટિ થઈ',
      poojaScheduled: 'સુનિશ્ચિત',
      goingLive: 'પૂજા લાઇવ',
      poojaCompleted: 'પૂર્ણ',
      recordingReady: 'રેકોર્ડિંગ તૈયાર',
      prasadPacked: 'પ્રસાદ પેક થયું',
      prasadDispatched: 'મોકલ્યું',
      prasadDelivered: 'વિતરિત',
      sankalpamDetails: 'સંકલ્પ વિગતો',
      poojaSeva: 'પૂજા સેવા',
      templeLocation: 'મંદિર સ્થાન',
      devoteeName: 'ભક્તનું નામ',
      gothramNakshatra: 'ગોત્ર / નક્ષત્ર',
      watchBroadcast: 'વિડિઓ પ્રસારણ જુઓ',
      trackPrasad: 'પ્રસાદ બોક્સ ટ્રેક કરો',
      sevaOfferedDesc: 'તમારી પૂજા વિનંતી ભક્તિપૂર્વક પ્રાપ્ત થઈ છે.',
      pujariAssignedDesc: 'તમારી સેવા ચલાવવા માટે પંડિત રમેશ શર્મા સોંપવામાં આવ્યા છે.',
      poojaScheduledDesc: 'સંકલ્પ ૧૫ એપ્રિલે સવારે ૯:૦૦ વાગ્યે સુનિશ્ચિત થયેલ છે.',
      goingLiveDesc: 'પવિત્ર લાઇવ પ્રસારણ કરવામાં આવ્યું હતું. આશીર્વાદ વહેંચવામાં આવ્યા.',
      poojaCompletedDesc: 'તમારા નામ અને ગોત્રમાં પૂજા સફળતાપૂર્વક કરવામાં આવી છે.',
      recordingReadyDesc: 'તમારું સમર્પિત પૂજા વિડિઓ આર્કાઇવ તૈયાર થઈ રહ્યું છે.',
      prasadPackedDesc: 'પવિત્ર પ્રસાદ દેવસેવા આશીર્વાદ બોક્સમાં પેક કરવામાં આવ્યો છે.',
      prasadDispatchedDesc: 'તમારો પ્રસાદ રસ્તામાં છે. ટ્રેકિંગ વિગતો બાકી છે.',
      prasadDeliveredDesc: 'પવિત્ર પ્રસાદ તમારા ઘરમાં શાંતિ લાવે.',
    },
    temples: {
      title: 'પવિત્ર મંદિરો',
      subtitle: 'દિવ્ય મંદિરોનું અન્વેષણ કરો',
      explore: 'અન્વેષણ કરો',
      hide: 'છુપાવો',
      availablePoojas: 'ઉપલબ્ધ પૂજા',
      location: 'સ્થાન',
    },
    profile: {
      title: 'પ્રોફાઇલ',
      personalisation: 'વ્યક્તિગતકરણ',
      aiRecommendations: 'તમારી પવિત્ર ભલામણો',
      settings: 'સેટિંગ્સ',
      theme: 'થીમ',
      darkMode: 'ડાર્ક મોડ',
      lightMode: 'લાઇટ મોડ',
      notifications: 'સૂચનાઓ',
      hinduCalendar: 'હિન્દુ કેલેન્ડર',
      helpSupport: 'સહાય અને સપોર્ટ',
      appSettings: 'એપ સેટિંગ્સ',
      signOut: 'સાઇન આઉટ',
      version: 'ભક્તિ સાથે બનાવેલ',
      editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
      editPersonalInfo: 'વ્યક્તિગત માહિતી સંપાદિત કરો',
      fullName: 'પૂરું નામ',
      email: 'ઇમેઇલ',
      phone: 'ફોન',
      location: 'સ્થાન',
      nakshatra: 'નક્ષત્ર',
      rashi: 'રાશિ',
      dateOfBirth: 'જન્મ તારીખ',
      gothram: 'ગોત્ર',
      saveChanges: 'ફેરફારો સાચવો',
      recommendationsTitle: 'તમારા નક્ષત્ર પર આધારિત',
      recommendationsDesc: 'તમારા માટે વ્યક્તિગત પૂજા ભલામણો',
      viewRecommendations: 'ભલામણો જુઓ',
      totalPoojas: 'પૂજા',
      upcomingCount: 'આગામી',
      devotionScore: 'ભક્તિ',
      ishtaDevatas: 'ઇષ્ટ દેવતાઓ (દેવતા પસંદગીઓ)',
      noDeities: 'હજી સુધી કોઈ દેવતાઓ પસંદ કર્યા નથી',
      selectIshtaDevatas: 'ઇષ્ટ દેવતાઓ પસંદ કરો',
      savePreferences: 'પસંદગીઓ સાચવો',
      val: {
        priya: 'પ્રિયા',
        raghavan: 'રાઘવન અય્યર',
        bangalore: 'બેંગલુરુ, કર્ણાટક',
        shravana: 'શ્રવણ',
        makara: 'મકર (મકર રાશિ)',
        dob: '15 જાન્યુઆરી 1990',
        bharadwaja: 'ભારદ્વાજ'
      }
    },
    notifications: {
      title: 'સૂચના સેટિંગ્સ',
      poojaReminders: 'પૂજા રીમાઇન્ડર્સ',
      poojaRemindersDesc: 'તમારી સુનિશ્ચિત પૂજા પહેલાં રીમાઇન્ડર મેળવો',
      liveStreams: 'લાઇવ સ્ટ્રીમ્સ',
      liveStreamsDesc: 'જ્યારે તમારી પૂજા સ્ટ્રીમિંગ શરૂ થાય ત્યારે સૂચના',
      prasadUpdates: 'પ્રસાદ અપડેટ્સ',
      prasadUpdatesDesc: 'તમારા પ્રસાદ ડિલિવરી સ્થિતિ ટ્રેક કરો',
      festivalAlerts: 'તહેવાર ચેતવણીઓ',
      festivalAlertsDesc: 'વિશેષ પૂજા અને તહેવાર સૂચનાઓ',
      saveSettings: 'સેટિંગ્સ સાચવો',
    },
    calendar: {
      title: 'હિન્દુ કેલેન્ડર',
      todayTithi: 'આજની તિથિ',
      upcomingFestivals: 'આગામી તહેવારો',
      shuklaPakshaChaturthi: 'શુક્લ પક્ષ ચતુર્થી',
      recommendedPoojas: 'ભલામણ કરેલ પૂજા',
      offerSeva: 'સેવા અર્પણ કરો',
      legendFestival: 'તહેવાર',
      legendEkadashi: 'એકાદશી',
      legendAmavasya: 'અમાવાસ્યા',
      legendPournami: 'પૂર્ણિમા',
      eventUgadiTitle: '૧૪ એપ્રિલ — ઉગાડી (તેલુગુ નવું વર્ષ)',
      eventUgadiDesc: 'તેલુગુ અને કન્નડ નવું વર્ષ. નવી શરૂઆત કરવા, મિલકત ખરીદવા અને વિશેષ પ્રાર્થના કરવા માટે અત્યંત શુભ દિવસ.',
      eventRamNavamiTitle: '૧૭ એપ્રિલ — શ્રી રામ નવમી',
      eventRamNavamiDesc: 'ભગવાન રામની જન્મજયંતી. શાંતિ, મનની શુદ્ધિ અને પવિત્ર નામોના જાપ માટે આદેશ.',
      eventAmavasyaTitle: '૧૮ એપ્રિલ — અમાવસ્યા',
      eventAmavasyaDesc: 'અમાવસ્યા. પિતૃઓના આશીર્વાદ મેળવવા, નકારાત્મક કર્મો મુક્ત કરવા અને શુદ્ધિ હવન કરવા માટે અત્યંત શક્તિશાળી સમય.',
      eventPournamiTitle: '૩ એપ્રિલ — પૂર્ણિમા',
      eventPournamiDesc: 'પૂર્ણિમા. દિવ્ય ઉર્જા મેળવવા, ધ્યાન કરવા અને પારિવારિક સમૃદ્ધિ માટે સત્યનારાયણ વ્રત રાખવા માટે શુભ.',
      eventEkadashiTitle: '{day} એપ્રિલ — એકાદશી',
      eventEkadashiDesc: 'ભગવાન વિષ્ણુને સમર્પિત એક પવિત્ર દિવસ. ઉપવાસ રાખવા, માનસિક સ્પષ્ટતા અને આધ્યાત્મિક પ્રગતિ માટે અત્યંત ફાયદાકારક.',
      dayTitle: '{day} એપ્રિલ',
      dayDesc: 'દૈનિક પ્રાર્થના, ધ્યાન અને મંદિરોમાં પવિત્ર અર્ચના કરવા માટે એક શુભ દિવસ.',
      april: 'એપ્રિલ',
      weekday0: 'ર',
      weekday1: 'સો',
      weekday2: 'મં',
      weekday3: 'બુ',
      weekday4: 'ગુ',
      weekday5: 'શુ',
      weekday6: 'શ',
    },
    festival: {
      ugadi: 'ઉગાડી',
      ugadiDesc: 'તેલુગુ અને કન્નડ નવું વર્ષ',
      ramNavami: 'શ્રી રામ નવમી',
      ramNavamiDesc: 'ભગવાન રામનો જન્મ',
      vishu: 'વિષુ',
      vishuDesc: 'મલયાલમ નવું વર્ષ',
      hanumanJayanti: 'હનુમાન જયંતી',
      hanumanJayantiDesc: 'ભગવાન હનુમાનનો જન્મ',
    },
    help: {
      title: 'સહાય અને સપોર્ટ',
      contactSupport: 'સપોર્ટનો સંપર્ક કરો',
      faq: 'વારંવાર પૂછાતા પ્રશ્નો',
      faq1Q: 'હું પૂજા કેવી રીતે બુક કરું?',
      faq1A: "પૂજા બ્રાઉઝ કરો, તમારા મનપસંદ મંદિર અને સમય પસંદ કરો, પછી તમારું બુકિંગ પૂર્ણ કરવા માટે 'આ પૂજા અર્પણ કરો' પર ક્લિક કરો.",
      faq2Q: 'શું હું પૂજા લાઇવ જોઈ શકું છું?',
      faq2A: "હા! જ્યારે તમારી પૂજા શરૂ થશે, ત્યારે તમને એક સૂચના મળશે. રીઅલ-ટાઇમમાં જોવા માટે તમારા બુકિંગમાં 'લાઇવ જુઓ' પર ક્લિક કરો.",
      faq3Q: 'પ્રસાદ કેવી રીતે વિતરિત કરવામાં આવે છે?',
      faq3A: 'તમારી પૂજા પૂર્ણ થયા પછી, પ્રસાદને કાળજીપૂર્વક પેક કરીને તમારા સરનામે મોકલવામાં આવે છે.',
    },
    language: {
      label: 'ભાષા',
      english: 'English',
      telugu: 'తెలుగు',
      hindi: 'हिंदी',
      gujarati: 'ગુજરાતી',
    },
    deity: {
      ganesha: 'ગણેશ',
      lakshmi: 'લક્ષ્મી',
      shiva: 'શિવ',
      vishnu: 'વિષ્ણુ',
      durga: 'દુર્ગા',
      saraswati: 'સરસ્વતી',
      hanuman: 'હનુમાન',
      murugan: 'મુરુગન',
    },
    poojaDb: {
      1: { title: 'રુદ્રાભિષેક', purpose: 'આધ્યાત્મિક શુદ્ધિ માટે ભગવાન શિવ માટે પવિત્ર સ્નાન વિધિ' },
      2: { title: 'વિષ્ણુ અભિષેક', purpose: 'સમૃદ્ધિ અને શાંતિ માટે ભગવાન વિષ્ણુ માટે દિવ્ય સ્નાન વિધિ' },
      3: { title: 'લક્ષ્મી અભિષેક', purpose: 'ધન આકર્ષવા માટે દેવી લક્ષ્મી માટે પવિત્ર સ્નાન વિધિ' },
      4: { title: 'ગણેશ અભિષેક', purpose: 'નવી શરૂઆત માટે વિઘ્નો દૂર કરો અને આશીર્વાદ મેળવો' },
      5: { title: 'સરસ્વતી અભિષેક', purpose: 'જ્ઞાન, ડહાપણ અને કલાત્મક ક્ષમતાઓમાં વધારો કરો' },
      6: { title: 'ગણપતિ હોમમ', purpose: 'વિઘ્નો દૂર કરવા અને પ્રયાસોમાં સફળતા સુનિશ્ચित કરવા માટે હવન વિધિ' },
      7: { title: 'નવગ્રહ હોમમ', purpose: 'ગ્રહોના પ્રભાવોને સંતુલિત કરે છે અને દોષો દૂર કરે છે' },
      8: { title: 'લક્ષ્મી કુબેરા હોમમ', purpose: 'ધન, સમૃદ્ધિ અને આર્થિક વિપુલતાને આકર્ષે છે' },
      9: { title: 'સુદર્શન હોમમ', purpose: 'નકારાત્મક ઉર્જા અને અનિષ્ટ શક્તિઓથી રક્ષણ' },
      10: { title: 'મહા મૃત્યુંજય હોમમ', purpose: 'આરોગ્ય, દીર્ઘાયુષ્ય અને મૃત્યુ પર વિજયને પ્રોત્સાહન આપે છે' },
      11: { title: 'સહસ્રનામ અર્ચના', purpose: 'દિવ્ય આશીર્વાદ માટે ભગવાન વિષ્ણુના ૧૦૦૦ નામોનું પઠન' },
      12: { title: 'લલિતા સહસ્રનામ અર્ચના', purpose: 'દિવ્ય સ્ત્રી શક્તિ અને આશીર્વાદનું આહ્વાન કરો' },
      13: { title: 'અષ્ટોત્તરા શતનામાવલી', purpose: 'ઝડપી આશીર્વાદ અને વિઘ્ન નિવારણ માટે ૧૦૮ નામો અર્પણ કરવા' },
      14: { title: 'હનુમાન ચાલીસા અર્ચના', purpose: 'મુશ્કેલીઓ સામે શક્તિ, હિંમત અને રક્ષણ મેળવો' },
      15: { title: 'દુર્ગા અષ્ટોત્તરા અર્ચના', purpose: 'રક્ષણ અને શક્તિ માટે દિવ્ય માતાના આશીર્વાદ' },
      16: { title: 'સત્યનારાયણ વ્રતમ્', purpose: 'ઇચ્છાઓની પૂર્તિ અને સમૃદ્ધિ માટે પૂર્ણ વ્રત' },
      17: { title: 'વરલક્ષ્મી વ્રતમ્', purpose: 'પારિવારિક સુખાકારી & વિપુલતા માટે વિશેષ વ્રત' },
      18: { title: 'કલશાભિષેક', purpose: 'પૂર્ણ શુદ્ધિ માટે પવિત્ર કળશ સાથે ભવ્ય અભિષેક' },
      19: { title: 'પ્રદોષમ વિશેષ પૂજા', purpose: 'પાપોમાંથી મુક્તિ માટે પ્રદોષ કાળ દરમિયાન કરવામાં આવે છે' },
      20: { title: 'એકાદશી વિશેષ પૂજા', purpose: 'આધ્યાત્મિક ઉન્નતિ માટે એકાદશી પર શુભ પૂજા' }
    },
    templeDb: {
      tirumala: { name: 'તિરુમલા મંદિર', location: 'આંધ્ર પ્રદેશ', deity: 'ભગવાન વેંકટેશ્વર', description: 'વિશ્વના સૌથી ધનિક અને સૌથી વધુ મુલાકાત લેવાતા તીર્થધામોમાંનું એક' },
      rameshwaram: { name: 'રામેશ્વરમ મંદિર', location: 'તમિલનાડુ', deity: 'ભગવાન શિવ', description: 'રામેશ્વરમ દ્વીપ પર પવિત્ર જ્યોતિર્લિંગ મંદિર' },
      madurai: { name: 'મદુરાઇ મંદિર', location: 'તમિલનાડુ', deity: 'દેવી મીનાક્ષી', description: 'મીનાક્ષીના રૂપમાં દેવી પાર્વતીને સમર્પિત ઐતિહાસિક મંદિર' },
      varanasi: { name: 'વારાણસી મંદિર', location: 'ઉત્તર પ્રદેશ', deity: 'ભગવાન શિવ', description: 'પવિત્ર ગંગા નદીના કિનારે આવેલું પ્રાચીન મંદિર' },
      siddhiVinayak: { name: 'સિદ્ધિ વિનાયક મંદિર', location: 'મહારાષ્ટ્ર', deity: 'ભગવાન ગણેશ', description: 'મંગળવારે મુંબઈમાં ભગવાન ગણેશને સમર્પિત પ્રખ્યાત મંદિર' }
    }
  }
};